import { execSync, spawnSync } from 'child_process';
import { writeFileSync, readFileSync, existsSync, mkdirSync, readdirSync } from 'fs';
import { join } from 'path';
import { COMPONENTS } from '@eve/dna';

export interface Route {
  path: string;
  target: string;
  domain?: string;
  ssl?: boolean;
}

// Paths on the HOST filesystem that are mounted into the Traefik container.
// Container sees these at /etc/traefik/* (mapped in the docker-compose volumes).
const HOST_CONFIG_DIR = '/opt/traefik';
const HOST_DYNAMIC_DIR = '/opt/traefik/dynamic';

// Paths as seen INSIDE the Traefik container (mounted from the host above).
const CONTAINER_DYNAMIC_DIR = '/etc/traefik/dynamic';
const CONTAINER_ACME_FILE = '/etc/traefik/acme.json';

/**
 * Finds the synap-backend API container (managed by the synap CLI's docker-compose,
 * project name = "synap-backend", service = "backend").
 * Returns the container name, or null if not running.
 */
function getSynapBackendContainer(): string | null {
  try {
    const out = execSync(
      `docker ps --filter "label=com.docker.compose.project=synap-backend" --filter "label=com.docker.compose.service=backend" --format "{{.Names}}"`,
      { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'ignore'] },
    ).trim();
    return out.split('\n')[0]?.trim() || null;
  } catch {
    return null;
  }
}

/** Connects a container to eve-network (no-op if already connected or container absent). */
function connectToEveNetwork(containerName: string): void {
  try {
    execSync(`docker network connect eve-network ${containerName}`, {
      stdio: ['pipe', 'pipe', 'ignore'],
    });
  } catch {
    // Already connected or container doesn't exist — both are fine
  }
}

// Private IP ranges we trust for forwarded headers in behind-proxy mode.
const TRUSTED_PROXY_IPS = [
  '10.0.0.0/8',
  '172.16.0.0/12',
  '192.168.0.0/16',
  '127.0.0.1/32',
];

function buildStaticConfig(ssl: boolean, email?: string): string {
  const acmeSection = ssl && email
    ? `
certificatesResolvers:
  letsencrypt:
    acme:
      email: ${email}
      storage: ${CONTAINER_ACME_FILE}
      tlsChallenge: {}
`
    : '';

  return `# Traefik static config — generated by Eve
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  file:
    directory: ${CONTAINER_DYNAMIC_DIR}
    watch: true
${acmeSection}
api:
  dashboard: true
  insecure: true

log:
  level: INFO

accessLog: {}
`.trimStart();
}

function buildProxyModeStaticConfig(): string {
  const trustedIps = TRUSTED_PROXY_IPS.map(ip => `        - "${ip}"`).join('\n');
  return `# Traefik static config — generated by Eve (behind-proxy mode)
# External proxy handles SSL termination. Traefik listens on HTTP only.
entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      trustedIPs:
${trustedIps}

providers:
  file:
    directory: ${CONTAINER_DYNAMIC_DIR}
    watch: true

api:
  dashboard: true
  insecure: true

log:
  level: INFO

accessLog: {}
`.trimStart();
}

export class TraefikService {
  private configDir: string;
  private traefikConfigPath: string;
  private dynamicConfigDir: string;

  constructor(configDir: string = HOST_CONFIG_DIR) {
    this.configDir = configDir;
    this.traefikConfigPath = join(configDir, 'traefik.yml');
    this.dynamicConfigDir = join(configDir, 'dynamic');
  }

  async install(): Promise<void> {
    console.log('Installing Traefik...');

    if (!existsSync(this.configDir)) mkdirSync(this.configDir, { recursive: true });
    if (!existsSync(this.dynamicConfigDir)) mkdirSync(this.dynamicConfigDir, { recursive: true });

    const isDokploy = existsSync('/opt/dokploy');
    if (isDokploy) {
      console.log('Detected Dokploy — using existing Traefik installation');
      await this.configureDokployTraefik();
    } else {
      await this.installStandalone();
    }

    console.log('Traefik installation complete');
  }

  private async installStandalone(): Promise<void> {
    writeFileSync(this.traefikConfigPath, buildStaticConfig(false));
    console.log('Created Traefik static config');

    try {
      execSync('docker network create eve-network', { stdio: 'ignore' });
    } catch { /* already exists */ }

    // Silent because the container often doesn't exist on first install or
    // after `domain repair` — surfacing "No such container" to the user is noise.
    spawnSync('docker', ['rm', '-f', 'eve-legs-traefik'], { stdio: 'ignore' });

    const result = spawnSync('docker', [
      'run', '-d',
      '--name', 'eve-legs-traefik',
      '--restart', 'unless-stopped',
      '-p', '80:80',
      '-p', '443:443',
      '-p', '8080:8080',
      '-v', '/var/run/docker.sock:/var/run/docker.sock:ro',
      '-v', `${this.configDir}/traefik.yml:/etc/traefik/traefik.yml:ro`,
      '-v', `${this.dynamicConfigDir}:/etc/traefik/dynamic:ro`,
      '-v', 'eve-legs-traefik-certs:/etc/traefik/acme.json',
      '--network', 'eve-network',
      'traefik:v3.0',
    ], { stdio: 'inherit' });

    if (result.status !== 0) throw new Error(`docker run exited with code ${result.status}`);
    console.log('Traefik container started');
  }

  private async configureDokployTraefik(): Promise<void> {
    console.log('Using Dokploy-managed Traefik');
  }

  async configureSubdomains(domain: string, ssl: boolean, email?: string, installedComponents?: string[], behindProxy = false): Promise<void> {
    // Synap backend runs in its own docker-compose project. Connect it to
    // eve-network so Traefik (also on eve-network) can resolve it by name.
    const synapContainer = getSynapBackendContainer();
    if (synapContainer) {
      connectToEveNetwork(synapContainer);
      console.log(`  Connected ${synapContainer} → eve-network`);
    } else if (!installedComponents || installedComponents.includes('synap')) {
      console.warn('  Warning: Synap backend container not found — pod.domain routing will 502 until `eve brain init` is run');
    }

    // Build routes from the component registry — single source of truth.
    // Every routed service (including the Eve dashboard) is a Docker container
    // on eve-network, addressable by its container name.
    const services: Array<{ id: string; subdomain: string; upstream: string; requires: string | null }> = [];

    for (const comp of COMPONENTS) {
      if (!comp.service || !comp.service.subdomain) continue;
      if (installedComponents && !installedComponents.includes(comp.id)) continue;

      let containerName = comp.service.containerName;
      if (comp.id === 'synap' && synapContainer) containerName = synapContainer;

      services.push({
        id: comp.id,
        subdomain: comp.service.subdomain,
        upstream: `http://${containerName}:${comp.service.internalPort}`,
        requires: comp.id,
      });
    }

    // Build routers:
    //   behindProxy: HTTP only, no redirects, no TLS — the upstream proxy handles that.
    //   ssl:         HTTP redirects → HTTPS, HTTPS carries real cert.
    //   plain:       HTTP + HTTPS with self-signed (less confusing than protocol error).
    const routersYaml = services.map(s => {
      const host = `${s.subdomain}.${domain}`;
      if (behindProxy) {
        // Single HTTP router — external proxy already terminated TLS.
        return (
          `    ${s.id}:\n` +
          `      rule: "Host(\`${host}\`)"\n` +
          `      entryPoints:\n` +
          `        - web\n` +
          `      service: ${s.id}-svc`
        );
      }
      if (ssl) {
        return (
          // HTTP → HTTPS redirect router
          `    ${s.id}-http:\n` +
          `      rule: "Host(\`${host}\`)"\n` +
          `      entryPoints:\n` +
          `        - web\n` +
          `      middlewares:\n` +
          `        - redirect-to-https\n` +
          `      service: ${s.id}-svc\n` +
          // HTTPS router with real cert
          `    ${s.id}:\n` +
          `      rule: "Host(\`${host}\`)"\n` +
          `      entryPoints:\n` +
          `        - websecure\n` +
          `      tls:\n` +
          `        certResolver: letsencrypt\n` +
          `      service: ${s.id}-svc`
        );
      }
      // No SSL: serve on HTTP, and also on HTTPS with Traefik's default
      // self-signed cert. Without tls: {}, Traefik won't terminate TLS for
      // websecure routers → browser gets ERR_SSL_PROTOCOL_ERROR instead of
      // a cert warning. With tls: {}, HTTPS works (browser warns about
      // self-signed cert) — far less confusing than a hard connection error.
      // Run `eve domain set <domain> --ssl --email <e>` to get a real cert.
      return (
        `    ${s.id}-http:\n` +
        `      rule: "Host(\`${host}\`)"\n` +
        `      entryPoints:\n` +
        `        - web\n` +
        `      service: ${s.id}-svc\n` +
        `    ${s.id}-https:\n` +
        `      rule: "Host(\`${host}\`)"\n` +
        `      entryPoints:\n` +
        `        - websecure\n` +
        `      tls: {}\n` +
        `      service: ${s.id}-svc`
      );
    }).join('\n');

    const servicesYaml = services.map(s =>
      `    ${s.id}-svc:\n` +
      `      loadBalancer:\n` +
      (behindProxy ? `        passHostHeader: true\n` : '') +
      `        servers:\n` +
      `          - url: "${s.upstream}"`
    ).join('\n');

    const middlewaresYaml = (!behindProxy && ssl)
      ? `  middlewares:\n    redirect-to-https:\n      redirectScheme:\n        scheme: https\n        permanent: true\n`
      : '';

    const modeComment = behindProxy ? 'behind-proxy' : ssl ? 'ssl' : 'plain';
    const dynamicConfig =
      `# Eve subdomain routes — generated by \`eve domain set\`\n` +
      `# Domain: ${domain} | Mode: ${modeComment}\n` +
      `http:\n` +
      `${middlewaresYaml}` +
      `  routers:\n${routersYaml}\n` +
      `  services:\n${servicesYaml}\n`;

    // Write static config (proxy mode skips SSL/cert sections)
    if (!existsSync(this.configDir)) mkdirSync(this.configDir, { recursive: true });
    writeFileSync(this.traefikConfigPath, behindProxy ? buildProxyModeStaticConfig() : buildStaticConfig(ssl, email));

    // Write dynamic routes config
    if (!existsSync(this.dynamicConfigDir)) mkdirSync(this.dynamicConfigDir, { recursive: true });
    writeFileSync(join(this.dynamicConfigDir, 'eve-routes.yml'), dynamicConfig, 'utf-8');

    // Restart Traefik so it picks up the updated static config + new volumes
    try {
      execSync('docker restart eve-legs-traefik', { stdio: 'ignore' });
      console.log('  Traefik restarted');
    } catch {
      console.warn('  Could not restart Traefik automatically — run: docker restart eve-legs-traefik');
    }
  }

  // ---------------------------------------------------------------------------
  // Proxy mode
  // ---------------------------------------------------------------------------

  /**
   * Detect whether Traefik is currently running in behind-proxy mode by
   * checking whether the static config has no `websecure` entrypoint.
   */
  getProxyModeStatus(): { enabled: boolean; ssl: boolean; entrypoints: string[] } {
    try {
      const config = readFileSync(this.traefikConfigPath, 'utf-8');
      const enabled = !config.includes('websecure');
      const ssl = config.includes('certificatesResolvers');
      return {
        enabled,
        ssl: !enabled && ssl,
        entrypoints: enabled ? ['web'] : ['web', 'websecure'],
      };
    } catch {
      return { enabled: false, ssl: false, entrypoints: [] };
    }
  }

  /**
   * Switch Traefik to behind-proxy mode:
   *   - HTTP-only static config (no websecure, no cert resolver, trusted IPs)
   *   - Dynamic routes without redirects or TLS
   *   - Recreate container without port 443 binding
   */
  async enableProxyMode(domain: string, installedComponents?: string[]): Promise<void> {
    if (!existsSync(this.configDir)) mkdirSync(this.configDir, { recursive: true });
    if (!existsSync(this.dynamicConfigDir)) mkdirSync(this.dynamicConfigDir, { recursive: true });

    writeFileSync(this.traefikConfigPath, buildProxyModeStaticConfig());

    const synapContainer = getSynapBackendContainer();
    if (synapContainer) connectToEveNetwork(synapContainer);

    // Rewrite routes — HTTP only, no SSL
    await this.configureSubdomains(domain, false, undefined, installedComponents, true);

    this.recreateTraefikContainer(['80:80', '8080:8080']);
  }

  /**
   * Restore standalone mode (Traefik handles its own SSL).
   */
  async disableProxyMode(domain: string, ssl: boolean, email?: string, installedComponents?: string[]): Promise<void> {
    if (!existsSync(this.configDir)) mkdirSync(this.configDir, { recursive: true });

    // configureSubdomains also rewrites the static config — no need to write separately.
    await this.configureSubdomains(domain, ssl, email, installedComponents, false);

    this.recreateTraefikContainer(['80:80', '443:443', '8080:8080']);
  }

  /** Stop + remove + relaunch the Traefik container with the given port bindings. */
  private recreateTraefikContainer(ports: string[]): void {
    spawnSync('docker', ['rm', '-f', 'eve-legs-traefik'], { stdio: 'ignore' });

    const result = spawnSync('docker', [
      'run', '-d',
      '--name', 'eve-legs-traefik',
      '--restart', 'unless-stopped',
      ...ports.flatMap(p => ['-p', p]),
      '-v', '/var/run/docker.sock:/var/run/docker.sock:ro',
      '-v', `${this.traefikConfigPath}:/etc/traefik/traefik.yml:ro`,
      '-v', `${this.dynamicConfigDir}:/etc/traefik/dynamic:ro`,
      '-v', 'eve-legs-traefik-certs:/etc/traefik/acme.json',
      '--network', 'eve-network',
      'traefik:v3.0',
    ], { stdio: 'inherit' });

    if (result.status !== 0) throw new Error(`docker run exited with code ${result.status}`);
  }

  // ---------------------------------------------------------------------------
  // Routes
  // ---------------------------------------------------------------------------

  async addRoute(route: Route): Promise<void> {
    const configFile = join(this.dynamicConfigDir, `${route.path.replace(/\//g, '_')}.yml`);
    const routeConfig =
      `http:\n` +
      `  routers:\n` +
      `    ${route.path.replace(/[^a-zA-Z0-9]/g, '_')}:\n` +
      `      rule: "Host(\`${route.domain || 'localhost'}\`) && PathPrefix(\`${route.path}\`)"\n` +
      `      service: ${route.path.replace(/[^a-zA-Z0-9]/g, '_')}\n` +
      (route.ssl ? `      tls: {}\n` : '') +
      `  services:\n` +
      `    ${route.path.replace(/[^a-zA-Z0-9]/g, '_')}:\n` +
      `      loadBalancer:\n` +
      `        servers:\n` +
      `          - url: "${route.target}"\n`;
    writeFileSync(configFile, routeConfig);
  }

  async removeRoute(path: string): Promise<void> {
    const configFile = join(this.dynamicConfigDir, `${path.replace(/\//g, '_')}.yml`);
    if (existsSync(configFile)) writeFileSync(configFile, '');
  }

  async configureDomain(domain: string): Promise<void> {
    const routes = this.getRoutes();
    for (const route of routes) await this.addRoute({ ...route, domain });
  }

  async enableSSL(): Promise<void> {
    const routes = this.getRoutes();
    for (const route of routes) {
      if (route.domain) await this.addRoute({ ...route, ssl: true });
    }
  }

  getRoutes(): Route[] {
    try {
      if (!existsSync(this.dynamicConfigDir)) return [];
      const files = readdirSafe(this.dynamicConfigDir).filter(f => f.endsWith('.yml'));
      return files.flatMap(file => {
        const content = readFileSync(join(this.dynamicConfigDir, file), 'utf-8');
        const pathMatch = content.match(/PathPrefix\(`(.+)`\)/);
        const urlMatch = content.match(/url: "(.+)"/);
        if (!pathMatch || !urlMatch) return [];
        return [{
          path: pathMatch[1],
          target: urlMatch[1],
          domain: content.match(/Host\(`(.+)`\)/)?.[1],
          ssl: content.includes('tls:'),
        }];
      });
    } catch {
      return [];
    }
  }

  getStatus(): { installed: boolean; running: boolean; domain: string | null; ssl: boolean; behindProxy: boolean; routes: Route[] } {
    const installed = existsSync(this.traefikConfigPath);
    let running = false;
    try {
      const out = execSync('docker ps --filter "name=eve-legs-traefik" --format "{{.Names}}"', { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'ignore'] }).trim();
      running = out.length > 0;
    } catch {}
    const routes = this.getRoutes();
    const proxyStatus = this.getProxyModeStatus();
    return {
      installed,
      running,
      domain: routes.find(r => r.domain)?.domain ?? null,
      ssl: routes.some(r => r.ssl),
      behindProxy: proxyStatus.enabled,
      routes,
    };
  }
}

function readdirSafe(dir: string): string[] {
  // `readdirSync` is imported at module top — using `require()` here was
  // a silent ESM/CJS bug: in the bundled ESM output, `require` is undefined,
  // every call threw ReferenceError, and the catch returned `[]` for what
  // was supposed to be a real directory listing.
  try {
    return readdirSync(dir) as string[];
  } catch {
    return [];
  }
}
