import { existsSync, mkdirSync, writeFileSync, copyFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import type { EveSecrets } from './secrets-contract.js';
import { readAgentKeyOrLegacy, readEveSecrets } from './secrets-contract.js';

/** Default Hub Protocol path on the Synap API host (Better Auth / Hub REST). */
export const DEFAULT_HUB_PATH = '/api/hub';

export function resolveHubBaseUrl(secrets: EveSecrets | null): string | undefined {
  if (secrets?.synap?.hubBaseUrl?.trim()) {
    return secrets.synap.hubBaseUrl.replace(/\/$/, '');
  }
  const base = secrets?.synap?.apiUrl?.replace(/\/$/, '');
  if (!base) return undefined;
  return `${base}${DEFAULT_HUB_PATH}`;
}

export function defaultSkillsDir(): string {
  return join(homedir(), '.eve', 'skills');
}

const SYNAP_SKILL_MD = `---
name: synap-hub
description: Call the Synap Data Pod via Hub Protocol (Bearer SYNAP_API_KEY). Use for memory, entities, and agent tools — not for raw SQL unless explicitly allowed.
---

# Synap Hub (Eve)

- **Base URL:** use environment variable \`HUB_BASE_URL\` (must include path, e.g. \`https://pod.example.com/api/hub\`).
- **Auth:** \`Authorization: Bearer\` + value from \`SYNAP_API_KEY\` (same key as OpenClaw / pod API key).
- **Docs:** see Synap Hub Protocol REST in your pod documentation.

Prefer small, idempotent requests. Do not exfiltrate keys.
`;

/**
 * Ensures ~/.eve/skills/synap/SKILL.md exists (OpenClaw-style layout; Claude Code can symlink into .claude/skills).
 */
export function ensureEveSkillsLayout(skillsDir: string = defaultSkillsDir()): void {
  const synapDir = join(skillsDir, 'synap');
  mkdirSync(synapDir, { recursive: true });
  const skillPath = join(synapDir, 'SKILL.md');
  if (!existsSync(skillPath)) {
    writeFileSync(skillPath, SYNAP_SKILL_MD, 'utf-8');
  }
}

/**
 * Dotenv for OpenCode / sandbox / any tool that reads `.env` in the project root.
 *
 * Uses the `coder` agent's key — one Hub identity for the local AI
 * coder regardless of which engine binary is selected via
 * `secrets.builder.codeEngine`. Falls back to the legacy single key
 * for installs that haven't migrated yet.
 */
export async function writeBuilderProjectEnv(projectDir: string, cwd: string = process.cwd()): Promise<void> {
  const secrets = await readEveSecrets(cwd);
  const hub = resolveHubBaseUrl(secrets);
  const skillsDir = secrets?.builder?.skillsDir ?? defaultSkillsDir();
  ensureEveSkillsLayout(skillsDir);

  const synapApiKey = await readAgentKeyOrLegacy('coder', cwd);

  const lines: string[] = [
    '# Generated by Eve — Synap Hub + workspace wiring',
    `SYNAP_API_URL=${secrets?.synap?.apiUrl ?? ''}`,
    `SYNAP_API_KEY=${synapApiKey}`,
    `HUB_BASE_URL=${hub ?? ''}`,
    `EVE_SKILLS_DIR=${skillsDir}`,
    `DOKPLOY_WEBHOOK_URL=${secrets?.builder?.dokployWebhookUrl ?? process.env.DOKPLOY_WEBHOOK_URL ?? ''}`,
    `DOKPLOY_API_URL=${secrets?.builder?.dokployApiUrl ?? ''}`,
    `DOKPLOY_API_KEY=${secrets?.builder?.dokployApiKey ?? ''}`,
    '',
  ];
  writeFileSync(join(projectDir, '.env'), lines.join('\n'), { mode: 0o600 });
}

/**
 * Writes `.eve/sandbox.env` for docker compose --env-file.
 *
 * The sandbox is a generic Eve work environment (no specific component
 * agent) — it uses the `eve` agent identity for Hub Protocol calls so
 * its activity attributes back to Eve itself. Falls back to legacy if
 * no per-agent eve key has been minted yet.
 */
export async function writeSandboxEnvFile(cwd: string = process.cwd()): Promise<string> {
  const secrets = await readEveSecrets(cwd);
  const hub = resolveHubBaseUrl(secrets);
  const skillsDir = secrets?.builder?.skillsDir ?? defaultSkillsDir();
  const workspaceDir = secrets?.builder?.workspaceDir ?? join(cwd, '.eve', 'workspace');
  ensureEveSkillsLayout(skillsDir);

  const synapApiKey = await readAgentKeyOrLegacy('eve', cwd);

  const eveDir = join(cwd, '.eve');
  mkdirSync(eveDir, { recursive: true });
  const path = join(eveDir, 'sandbox.env');
  const lines = [
    `SYNAP_API_URL=${secrets?.synap?.apiUrl ?? ''}`,
    `SYNAP_API_KEY=${synapApiKey}`,
    `HUB_BASE_URL=${hub ?? ''}`,
    `EVE_SKILLS_DIR=${skillsDir}`,
    `EVE_WORKSPACE_DIR=${workspaceDir}`,
    `DOKPLOY_WEBHOOK_URL=${secrets?.builder?.dokployWebhookUrl ?? process.env.DOKPLOY_WEBHOOK_URL ?? ''}`,
  ];
  writeFileSync(path, lines.join('\n') + '\n', { mode: 0o600 });
  return path;
}

/**
 * Claude Code loads skills from `<project>/.claude/skills/<name>/SKILL.md` (see code.claude.com docs).
 * Copies the Eve synap stub into the project (portable; no symlink privileges).
 */
export function copySynapSkillIntoClaudeProject(projectDir: string, skillsDir: string = defaultSkillsDir()): void {
  ensureEveSkillsLayout(skillsDir);
  const src = join(skillsDir, 'synap', 'SKILL.md');
  const destDir = join(projectDir, '.claude', 'skills', 'synap');
  mkdirSync(destDir, { recursive: true });
  const dest = join(destDir, 'SKILL.md');
  copyFileSync(src, dest);
}

/**
 * Claude Code `settings.json` env block (see https://code.claude.com/docs/en/settings ).
 *
 * Uses the unified `coder` agent's Hub key — one identity for the local
 * AI coder regardless of which engine binary is selected via
 * `secrets.builder.codeEngine`. Falls back to the legacy single key for
 * installs that haven't migrated yet.
 */
export async function writeClaudeCodeSettings(projectDir: string, cwd: string = process.cwd()): Promise<void> {
  const secrets = await readEveSecrets(cwd);
  const hub = resolveHubBaseUrl(secrets);
  const synapApiKey = await readAgentKeyOrLegacy('coder', cwd);
  const dir = join(projectDir, '.claude');
  mkdirSync(dir, { recursive: true });
  const settings = {
    env: {
      SYNAP_API_URL: secrets?.synap?.apiUrl ?? '',
      SYNAP_API_KEY: synapApiKey,
      HUB_BASE_URL: hub ?? '',
      EVE_SKILLS_DIR: secrets?.builder?.skillsDir ?? defaultSkillsDir(),
    },
  };
  writeFileSync(join(dir, 'settings.json'), JSON.stringify(settings, null, 2), 'utf-8');
}

/**
 * Dotenv for Hermes daemon — reads secrets and writes `.eve/hermes.env` for docker compose `env_file`.
 *
 * Uses the `hermes` agent's key (its own user + scopes on the pod),
 * minted by the post-install hook in @eve/lifecycle. Falls back to
 * legacy only for installs that haven't migrated yet.
 */
export async function writeHermesEnvFile(cwd: string = process.cwd()): Promise<string> {
  const secrets = await readEveSecrets(cwd);
  const hub = resolveHubBaseUrl(secrets);
  const hermesConfig = secrets?.builder?.hermes;
  const synapApiKey = await readAgentKeyOrLegacy('hermes', cwd);

  const eveDir = join(cwd, '.eve');
  mkdirSync(eveDir, { recursive: true });
  const path = join(eveDir, 'hermes.env');
  const lines = [
    `SYNAP_API_URL=${secrets?.synap?.apiUrl ?? ''}`,
    `SYNAP_API_KEY=${synapApiKey}`,
    `HUB_BASE_URL=${hub ?? ''}`,
    `HERMES_ENABLED=${hermesConfig?.enabled ?? true}`,
    `HERMES_POLL_INTERVAL_MS=${hermesConfig?.pollIntervalMs ?? 30000}`,
    `HERMES_MAX_CONCURRENT_TASKS=${hermesConfig?.maxConcurrentTasks ?? 1}`,
    `EVE_WORKSPACE_DIR=${secrets?.builder?.workspaceDir ?? join(cwd, '.eve', 'workspace')}`,
    '',
  ];
  writeFileSync(path, lines.join('\n'), { mode: 0o600 });
  return path;
}
