import { existsSync, mkdirSync, writeFileSync, copyFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { randomBytes } from 'node:crypto';
import type { EveSecrets } from './secrets-contract.js';
import { readAgentKeyOrLegacy, readAgentKeyOrLegacySync, readEveSecrets, writeEveSecrets } from './secrets-contract.js';
import { resolveSynapUrl } from './components.js';

/** Default Hub Protocol path on the Synap API host (Better Auth / Hub REST). */
export const DEFAULT_HUB_PATH = '/api/hub';

export function resolveHubBaseUrl(secrets: EveSecrets | null): string | undefined {
  if (secrets?.synap?.hubBaseUrl?.trim()) {
    return secrets.synap.hubBaseUrl.replace(/\/$/, '');
  }
  const base = resolveSynapUrl(secrets).replace(/\/$/, '');
  if (!base) return undefined;
  return `${base}${DEFAULT_HUB_PATH}`;
}

export function defaultSkillsDir(): string {
  return join(homedir(), '.eve', 'skills');
}

/**
 * Fetches the bundled skill packages from the pod and writes them into
 * the local skills directory (~/.eve/skills/).
 *
 * If the pod is unreachable, falls back to the embedded stub so
 * Hermes / Claude Code always have at least a minimal Hub reference.
 *
 * Directory layout written:
 *   ~/.eve/skills/synap/SKILL.md            ← core data + memory + channels
 *   ~/.eve/skills/synap/governance.md
 *   ~/.eve/skills/synap/linking.md
 *   ~/.eve/skills/synap/capture.md
 *   ~/.eve/skills/synap-schema/SKILL.md     ← profiles + property defs
 *   ~/.eve/skills/synap-schema/property-types.md
 *   ~/.eve/skills/synap-ui/SKILL.md         ← views + dashboards
 */
export async function ensureEveSkillsLayout(
  skillsDir: string = defaultSkillsDir(),
  hubBaseUrl?: string,
  apiKey?: string,
): Promise<void> {
  // Always ensure the synap dir exists as a fallback
  mkdirSync(join(skillsDir, 'synap'), { recursive: true });

  if (hubBaseUrl && apiKey) {
    try {
      const res = await fetch(`${hubBaseUrl}/skills/system`, {
        headers: { Authorization: `Bearer ${apiKey}` },
        signal: AbortSignal.timeout(8000),
      });
      if (res.ok) {
        const packages = await res.json() as Array<{
          slug: string;
          files: Array<{ path: string; content: string }>;
        }>;
        for (const pkg of packages) {
          const pkgDir = join(skillsDir, pkg.slug);
          mkdirSync(pkgDir, { recursive: true });
          for (const file of pkg.files) {
            writeFileSync(join(pkgDir, file.path), file.content, 'utf-8');
          }
        }
        return;
      }
    } catch {
      // pod unreachable — fall through to stub
    }
  }

  // Fallback stub: minimal Hub Protocol reference
  const stubPath = join(skillsDir, 'synap', 'SKILL.md');
  if (!existsSync(stubPath)) {
    writeFileSync(stubPath, `---
name: synap
description: Use for memory, entities, channels, search, and governance via the Synap Hub Protocol.
---

# Synap Hub Protocol

Base URL: $HUB_BASE_URL
Auth: Authorization: Bearer $SYNAP_API_KEY

Key endpoints:
  GET  /memory?query=...          full-text search facts
  POST /memory                    store a fact
  GET  /entities/search?q=...     search entities
  POST /entities                  create entity
  GET  /entities/:id
  PUT  /entities/:id              update entity (merges)
  GET  /channels?workspaceId=...  list channels
  POST /skills/:id/execute        run a user skill
  GET  /skills/system             list system skill docs
  GET  /profiles                  list entity types

Run GET /users/me + GET /workspaces on startup to orient yourself.
`, 'utf-8');
  }
}

/**
 * Dotenv for OpenCode / sandbox / any tool that reads `.env` in the project root.
 *
 * Uses the `coder` agent's key — one Hub identity for the local AI
 * coder regardless of which engine binary is selected via
 * `secrets.builder.codeEngine`. Falls back to the legacy single key
 * for installs that haven't migrated yet.
 */
export async function writeBuilderProjectEnv(projectDir: string, cwd: string = process.cwd()): Promise<void> {
  const secrets = await readEveSecrets(cwd);
  const hub = resolveHubBaseUrl(secrets);
  const skillsDir = secrets?.builder?.skillsDir ?? defaultSkillsDir();
  const synapApiKeyForSkills = await readAgentKeyOrLegacy('coder', cwd);
  await ensureEveSkillsLayout(skillsDir, hub, synapApiKeyForSkills);

  const synapApiKey = await readAgentKeyOrLegacy('coder', cwd);

  const lines: string[] = [
    '# Generated by Eve — Synap Hub + workspace wiring',
    `SYNAP_API_URL=${resolveSynapUrl(secrets)}`,
    `SYNAP_API_KEY=${synapApiKey}`,
    `HUB_BASE_URL=${hub ?? ''}`,
    `EVE_SKILLS_DIR=${skillsDir}`,
    `DOKPLOY_WEBHOOK_URL=${secrets?.builder?.dokployWebhookUrl ?? process.env.DOKPLOY_WEBHOOK_URL ?? ''}`,
    `DOKPLOY_API_URL=${secrets?.builder?.dokployApiUrl ?? ''}`,
    `DOKPLOY_API_KEY=${secrets?.builder?.dokployApiKey ?? ''}`,
    '',
  ];
  writeFileSync(join(projectDir, '.env'), lines.join('\n'), { mode: 0o600 });
}

/**
 * Writes `.eve/sandbox.env` for docker compose --env-file.
 *
 * The sandbox is a generic Eve work environment (no specific component
 * agent) — it uses the `eve` agent identity for Hub Protocol calls so
 * its activity attributes back to Eve itself. Falls back to legacy if
 * no per-agent eve key has been minted yet.
 */
export async function writeSandboxEnvFile(cwd: string = process.cwd()): Promise<string> {
  const secrets = await readEveSecrets(cwd);
  const hub = resolveHubBaseUrl(secrets);
  const skillsDir = secrets?.builder?.skillsDir ?? defaultSkillsDir();
  const workspaceDir = secrets?.builder?.workspaceDir ?? join(cwd, '.eve', 'workspace');
  const synapApiKeyForSkills = await readAgentKeyOrLegacy('eve', cwd);
  await ensureEveSkillsLayout(skillsDir, hub, synapApiKeyForSkills);

  const synapApiKey = await readAgentKeyOrLegacy('eve', cwd);

  const eveDir = join(cwd, '.eve');
  mkdirSync(eveDir, { recursive: true });
  const path = join(eveDir, 'sandbox.env');
  const lines = [
    `SYNAP_API_URL=${resolveSynapUrl(secrets)}`,
    `SYNAP_API_KEY=${synapApiKey}`,
    `HUB_BASE_URL=${hub ?? ''}`,
    `EVE_SKILLS_DIR=${skillsDir}`,
    `EVE_WORKSPACE_DIR=${workspaceDir}`,
    `DOKPLOY_WEBHOOK_URL=${secrets?.builder?.dokployWebhookUrl ?? process.env.DOKPLOY_WEBHOOK_URL ?? ''}`,
  ];
  writeFileSync(path, lines.join('\n') + '\n', { mode: 0o600 });
  return path;
}

/**
 * Claude Code loads skills from `<project>/.claude/skills/<name>/SKILL.md`.
 * Copies all Synap skill packages (synap, synap-schema, synap-ui) into the project.
 * Call after ensureEveSkillsLayout() has already written files to skillsDir.
 */
export function copySynapSkillIntoClaudeProject(projectDir: string, skillsDir: string = defaultSkillsDir()): void {
  const { readdirSync: _readdirSync, statSync: _statSync } = require('node:fs') as typeof import('node:fs');
  const skillPkgs = ['synap', 'synap-schema', 'synap-ui'];
  for (const pkg of skillPkgs) {
    const srcDir = join(skillsDir, pkg);
    const destDir = join(projectDir, '.claude', 'skills', pkg);
    try {
      const files = _readdirSync(srcDir);
      mkdirSync(destDir, { recursive: true });
      for (const file of files) {
        if (file.endsWith('.md')) {
          copyFileSync(join(srcDir, file), join(destDir, file));
        }
      }
    } catch {
      // skill package not yet fetched — skip silently
    }
  }
}

/**
 * Claude Code `settings.json` env block (see https://code.claude.com/docs/en/settings ).
 *
 * Uses the unified `coder` agent's Hub key — one identity for the local
 * AI coder regardless of which engine binary is selected via
 * `secrets.builder.codeEngine`. Falls back to the legacy single key for
 * installs that haven't migrated yet.
 */
export async function writeClaudeCodeSettings(projectDir: string, cwd: string = process.cwd()): Promise<void> {
  const secrets = await readEveSecrets(cwd);
  const hub = resolveHubBaseUrl(secrets);
  const synapApiKey = await readAgentKeyOrLegacy('coder', cwd);
  const skillsDir = secrets?.builder?.skillsDir ?? defaultSkillsDir();
  const dir = join(projectDir, '.claude');
  mkdirSync(dir, { recursive: true });

  const settings = {
    env: {
      SYNAP_API_URL: resolveSynapUrl(secrets),
      SYNAP_API_KEY: synapApiKey,
      HUB_BASE_URL: hub ?? '',
      EVE_SKILLS_DIR: skillsDir,
    },
  };
  writeFileSync(join(dir, 'settings.json'), JSON.stringify(settings, null, 2), 'utf-8');

  // If Hermes is installed, register its MCP server so Claude Code can call Hermes tools
  const hermesApiKey = secrets?.builder?.hermes?.apiServerKey;
  if (hermesApiKey) {
    const mcpServersDir = join(dir, 'mcp-servers');
    mkdirSync(mcpServersDir, { recursive: true });
    const hermesMcp = {
      type: 'http',
      url: 'http://localhost:9120',
      name: 'hermes',
      description: 'Hermes agent — memory, channels, skills via Synap Hub Protocol',
      headers: { Authorization: `Bearer ${hermesApiKey}` },
    };
    writeFileSync(join(mcpServersDir, 'hermes.json'), JSON.stringify(hermesMcp, null, 2), 'utf-8');
  }
}

/**
 * Dotenv for Hermes daemon — reads secrets and writes `~/.eve/hermes.env`
 * for docker compose `env_file`. Injects Hub credentials, AI config, and
 * centralised channel tokens so Hermes can serve Telegram/Discord/etc without
 * storing its own copy of the credentials.
 *
 * Channel routing: `secrets.channelRouting` maps platform → agent-slug. If the
 * target agent is `hermes` (or no routing entry exists), channel env vars are
 * injected. This keeps Hermes stateless relative to channel credentials while
 * remaining trivially swappable — change the routing entry and re-run to
 * redirect a platform to another agent without touching Hermes config.
 */
export async function writeHermesEnvFile(cwd: string = process.cwd()): Promise<string> {
  const secrets = await readEveSecrets(cwd);
  const hub = resolveHubBaseUrl(secrets);
  const hermesConfig = secrets?.builder?.hermes;
  const synapApiKey = await readAgentKeyOrLegacy('hermes', cwd);

  // Ensure a stable API_SERVER_KEY exists — generated once at first write,
  // then reused so OpenWebUI (and other consumers) don't need reconfiguring.
  let apiServerKey = hermesConfig?.apiServerKey;
  if (!apiServerKey) {
    apiServerKey = randomBytes(32).toString('hex');
    await writeEveSecrets({
      builder: { hermes: { ...(hermesConfig ?? {}), apiServerKey } },
    });
  }

  // Output always goes to ~/.eve/hermes.env — the same location docker run
  // expects (join(homedir(), '.eve', 'hermes.env')). cwd is only used above
  // for reading secrets, not for the output path.
  const eveDir = join(homedir(), '.eve');
  mkdirSync(eveDir, { recursive: true });
  const path = join(eveDir, 'hermes.env');

  const lines: string[] = [
    `SYNAP_API_URL=${resolveSynapUrl(secrets)}`,
    `SYNAP_API_KEY=${synapApiKey}`,
    `HUB_BASE_URL=${hub ?? ''}`,
    `HERMES_ENABLED=${hermesConfig?.enabled ?? true}`,
    `HERMES_POLL_INTERVAL_MS=${hermesConfig?.pollIntervalMs ?? 30000}`,
    `HERMES_MAX_CONCURRENT_TASKS=${hermesConfig?.maxConcurrentTasks ?? 1}`,
    `EVE_WORKSPACE_DIR=${secrets?.builder?.workspaceDir ?? join(homedir(), '.eve', 'workspace')}`,
    // API server key — clients (OpenWebUI, LobeChat, etc.) use this to call
    // the Hermes OpenAI-compat gateway at port 8642.
    `API_SERVER_ENABLED=true`,
    `API_SERVER_HOST=0.0.0.0`,
    `API_SERVER_PORT=8642`,
    `API_SERVER_KEY=${apiServerKey}`,
    // Hermes gateway is already behind OpenWebUI's auth layer — OWUI enforces
    // login before any request reaches the gateway. Allow all at the gateway
    // level so OWUI-proxied requests aren't double-rejected.
    `GATEWAY_ALLOW_ALL_USERS=true`,
  ];

  // Embedding model for semantic memory search. Only set for providers whose
  // models produce 1536-d vectors via the OpenAI-compat gateway — which is
  // the dimension the knowledge_facts pgvector column expects. Ollama
  // embedding models are typically 768–1024-d so we leave it empty there
  // and the plugin falls back to full-text search automatically.
  const hermesProvider =
    secrets?.ai?.serviceProviders?.['hermes'] ?? secrets?.ai?.defaultProvider;
  if (hermesProvider === 'openai' || hermesProvider === 'openrouter') {
    lines.push(`SYNAP_EMBED_MODEL=text-embedding-3-small`);
  }

  // Inject centralised channel credentials for each platform routed to hermes
  // (or defaulting to hermes when no routing entry is set).
  const routing = secrets?.channels ? buildChannelRouting(secrets) : {};
  const channels = secrets?.channels ?? {};

  if (channels.telegram?.enabled && routing.telegram === 'hermes') {
    lines.push(`TELEGRAM_BOT_TOKEN=${channels.telegram.botToken ?? ''}`);
    if (channels.telegram.webhookSecret) {
      lines.push(`TELEGRAM_WEBHOOK_SECRET=${channels.telegram.webhookSecret}`);
    }
  }
  if (channels.discord?.enabled && routing.discord === 'hermes') {
    lines.push(`DISCORD_BOT_TOKEN=${channels.discord.botToken ?? ''}`);
    if (channels.discord.guildId) lines.push(`DISCORD_GUILD_ID=${channels.discord.guildId}`);
    if (channels.discord.applicationId) lines.push(`DISCORD_APPLICATION_ID=${channels.discord.applicationId}`);
  }
  if (channels.whatsapp?.enabled && routing.whatsapp === 'hermes') {
    lines.push(`WHATSAPP_PHONE_NUMBER_ID=${channels.whatsapp.phoneNumberId ?? ''}`);
    lines.push(`WHATSAPP_ACCESS_TOKEN=${channels.whatsapp.accessToken ?? ''}`);
    if (channels.whatsapp.verifyToken) lines.push(`WHATSAPP_VERIFY_TOKEN=${channels.whatsapp.verifyToken}`);
  }
  if (channels.signal?.enabled && routing.signal === 'hermes') {
    lines.push(`SIGNAL_PHONE_NUMBER=${channels.signal.phoneNumber ?? ''}`);
    lines.push(`SIGNAL_API_URL=${channels.signal.apiUrl ?? ''}`);
  }
  if (channels.matrix?.enabled && routing.matrix === 'hermes') {
    lines.push(`MATRIX_HOMESERVER_URL=${channels.matrix.homeserverUrl ?? ''}`);
    lines.push(`MATRIX_ACCESS_TOKEN=${channels.matrix.accessToken ?? ''}`);
    if (channels.matrix.roomId) lines.push(`MATRIX_ROOM_ID=${channels.matrix.roomId}`);
  }
  if (channels.slack?.enabled && routing.slack === 'hermes') {
    lines.push(`SLACK_BOT_TOKEN=${channels.slack.botToken ?? ''}`);
    lines.push(`SLACK_SIGNING_SECRET=${channels.slack.signingSecret ?? ''}`);
    if (channels.slack.appToken) lines.push(`SLACK_APP_TOKEN=${channels.slack.appToken}`);
  }

  lines.push('');
  writeFileSync(path, lines.join('\n'), { mode: 0o600 });
  return path;
}

/**
 * Resolve effective channel routing: for each platform, return the target
 * agent slug. Falls back to 'hermes' when no explicit routing is configured.
 */
function buildChannelRouting(secrets: EveSecrets): Record<string, string> {
  const platforms = ['telegram', 'discord', 'whatsapp', 'signal', 'matrix', 'slack'] as const;
  const result: Record<string, string> = {};
  for (const p of platforms) {
    result[p] = secrets.channelRouting?.[p] ?? 'hermes';
  }
  return result;
}

// ---------------------------------------------------------------------------
// Hermes config + Synap memory plugin generation
// ---------------------------------------------------------------------------

const HERMES_CONFIG_YAML = (
  model: string,
  baseUrl: string,
  apiKey: string,
) => `# Hermes config — managed by Eve (eve install / eve ai apply)
# Editing this file directly is fine; Eve will overwrite the managed sections on the next apply.

memory:
  # Synap memory provider: 100% of memory syncs go to the Data Pod.
  # The synap plugin lives at $HERMES_HOME/plugins/memory/synap/
  provider: synap

# Named provider entry — Hermes resolves credentials from here, not from model.base_url/api_key.
# Both the main model and auxiliary clients (vision, web-extract) look up "custom/main".
providers:
  main:
    base_url: ${baseUrl}
    api_key: ${apiKey}
    model: ${model}

model:
  provider: custom:main
  default: ${model}

# MCP server — exposes Hermes tools to Claude Code, Cursor, and any MCP client.
# Connect at http://localhost:9120 (host) or http://eve-builder-hermes:9120 (docker network).
mcp:
  server:
    enabled: true
    port: 9120
    host: 0.0.0.0

# Hermes dashboard — admin UI
dashboard:
  port: 9119

# Skills — Synap Hub Protocol reference docs (mounted from ~/.eve/skills).
# Lives at /opt/data/synap-skills/ inside the container so it doesn't
# shadow Hermes's own /opt/data/skills/ bundled-skills directory (writable,
# managed by Hermes; we'd block its 91-skill bootstrap copy if we mounted
# the read-only Synap docs there).
skills:
  dir: /opt/data/synap-skills
`;

/**
 * Writes `~/.eve/hermes/config.yaml` — Hermes picks this up at startup
 * (via HERMES_HOME=/opt/data → /opt/data/config.yaml inside container,
 * which maps to ~/.eve/hermes/config.yaml on the host).
 *
 * Sets `memory.provider: synap` so every conversation turn is forwarded
 * to the Synap Data Pod via the plugin. Model block points Hermes at
 * Synap IS as the OpenAI-compat backend (same hub used by all components).
 */
export async function writeHermesConfigYaml(cwd: string = process.cwd()): Promise<string> {
  const secrets = await readEveSecrets(cwd);
  return writeHermesConfigYamlSync(secrets);
}

/**
 * Synchronous variant used by `wireComponentAi('hermes')`.
 *
 * That path removes/recreates the Docker container immediately after writing
 * config, so config.yaml must be fully written before `docker run` starts.
 */
export function writeHermesConfigYamlSync(secrets: EveSecrets | null): string {
  // Resolve effective AI provider for Hermes:
  //   1. Per-service override (serviceProviders.hermes)
  //   2. Global default (defaultProvider)
  //   3. First enabled provider in the list (handles the common case where the
  //      user added a provider via the UI but defaultProvider was not set)
  type ProviderEntry = { id: string; enabled?: boolean; apiKey?: string; baseUrl?: string; defaultModel?: string };
  const providers = (secrets?.ai?.providers ?? []) as ProviderEntry[];
  const implicitDefault = providers.find(p => p.enabled !== false)?.id ?? '';
  const providerId =
    secrets?.ai?.serviceProviders?.['hermes'] ??
    secrets?.ai?.defaultProvider ??
    implicitDefault;
  const provider = providers.find(p => p.id === providerId);

  // Well-known base URLs for built-in providers. Ollama uses the Docker-network
  // container name so the Hermes container can resolve it — `localhost` inside
  // the container resolves to itself, not the Ollama process on the host.
  const BUILTIN_URLS: Record<string, string> = {
    openrouter: 'https://openrouter.ai/api/v1',
    openai: 'https://api.openai.com/v1',
    anthropic: 'https://api.anthropic.com/v1',
    ollama: 'http://eve-brain-ollama:11434/v1',
  };

  let baseUrl = provider?.baseUrl?.replace(/\/$/, '') ?? BUILTIN_URLS[providerId] ?? '';

  // Rewrite host-loopback Ollama URLs for the container context.
  if (providerId === 'ollama' && /localhost|127\.0\.0\.1/.test(baseUrl)) {
    baseUrl = baseUrl.replace(/localhost|127\.0\.0\.1/, 'eve-brain-ollama');
  }

  const serviceModels = secrets?.ai?.serviceModels ?? {};

  let model: string;
  let resolvedBaseUrl: string;
  let modelApiKey: string;

  if (baseUrl) {
    // External LLM provider is configured — use its URL, key, and model.
    // The Synap Hub key lives in hermes.env (SYNAP_API_KEY) and is used by
    // the memory plugin; the model block needs the LLM provider's own key.
    model = serviceModels['hermes'] ?? provider?.defaultModel ?? 'hermes-3-llama-3.1-8b';
    resolvedBaseUrl = baseUrl;
    modelApiKey = provider?.apiKey ?? '';
  } else {
    // No external provider configured — fall back to the Synap IS proxy path.
    // This preserves behaviour for installs that haven't set up an AI provider yet.
    const synapUrl = resolveSynapUrl(secrets);
    resolvedBaseUrl = synapUrl ? `${synapUrl.replace(/\/$/, '')}/v1` : 'http://eve-brain-synap:4000/v1';
    model = serviceModels['hermes'] ?? 'synap/balanced';
    modelApiKey = readAgentKeyOrLegacySync('hermes', secrets);
  }

  const hermesDir = join(homedir(), '.eve', 'hermes');
  mkdirSync(hermesDir, { recursive: true });
  const configPath = join(hermesDir, 'config.yaml');
  writeFileSync(configPath, HERMES_CONFIG_YAML(model, resolvedBaseUrl, modelApiKey), { mode: 0o600 });
  return configPath;
}

// ---------------------------------------------------------------------------
// Synap memory provider plugin (Python)
// ---------------------------------------------------------------------------

const SYNAP_PLUGIN_YAML = `name: synap
version: 2.0.0
description: Synap Data Pod — complete tool suite for entity management, memory, channels, views, governance, and more via Hub Protocol.
hooks:
  - sync_turn
  - on_session_end
  - on_memory_write
  - prefetch
  - get_tool_schemas
  - handle_tool_call
`;

const SYNAP_PROVIDER_PY = `"""
Synap Data Pod — Hermes MemoryProvider plugin (tool suite v2).

Generated by Eve (eve install / eve ai apply). Do not edit manually;
re-run the install flow to regenerate.

This plugin receives 100% of Hermes memory syncs and forwards them to
the Synap Data Pod via Hub Protocol. It also exposes a full tool suite
(22 tools) covering entity management, memory, channels, views, documents,
knowledge, search, and governance — so Hermes can act as a complete
Synap agent, not just a memory relay.

Env vars read at runtime (injected by Eve into hermes.env):
  SYNAP_API_KEY      — Hub Protocol bearer token (hermes agent identity)
  HUB_BASE_URL       — e.g. https://pod.example.com/api/hub
  API_SERVER_KEY     — Hermes gateway auth key (used for embedding calls)
  SYNAP_EMBED_MODEL  — OpenAI-compat embedding model (empty = full-text only)
                       Set to text-embedding-3-small for openai/openrouter providers.
                       Left empty for ollama (models are not 1536-d).
"""
import os
import json
import urllib.request
import urllib.parse
import urllib.error
from typing import Any


# ---------------------------------------------------------------------------
# Module-level HTTP helpers
# ---------------------------------------------------------------------------

def _hub_url(path: str) -> str:
    base = os.environ.get("HUB_BASE_URL", "").rstrip("/")
    return f"{base}{path}"


def _headers() -> dict[str, str]:
    return {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {os.environ.get('SYNAP_API_KEY', '')}",
    }


def _post(path: str, payload: dict) -> Any:
    """POST JSON payload to Hub Protocol."""
    try:
        data = json.dumps(payload).encode()
        req = urllib.request.Request(_hub_url(path), data=data, headers=_headers(), method="POST")
        with urllib.request.urlopen(req, timeout=10) as resp:
            return json.loads(resp.read())
    except (urllib.error.URLError, Exception):
        return None


def _get(path: str, params: dict | None = None) -> Any:
    """GET request with optional query params dict."""
    try:
        url = _hub_url(path)
        if params:
            url = f"{url}?{urllib.parse.urlencode(params)}"
        req = urllib.request.Request(url, headers=_headers(), method="GET")
        with urllib.request.urlopen(req, timeout=10) as resp:
            return json.loads(resp.read())
    except (urllib.error.URLError, Exception):
        return None


def _put(path: str, payload: dict) -> Any:
    """PUT JSON payload to Hub Protocol."""
    try:
        data = json.dumps(payload).encode()
        req = urllib.request.Request(_hub_url(path), data=data, headers=_headers(), method="PUT")
        with urllib.request.urlopen(req, timeout=10) as resp:
            return json.loads(resp.read())
    except (urllib.error.URLError, Exception):
        return None


def _patch(path: str, payload: dict) -> Any:
    """PATCH JSON payload to Hub Protocol."""
    try:
        data = json.dumps(payload).encode()
        req = urllib.request.Request(_hub_url(path), data=data, headers=_headers(), method="PATCH")
        with urllib.request.urlopen(req, timeout=10) as resp:
            return json.loads(resp.read())
    except (urllib.error.URLError, Exception):
        return None


def _delete(path: str) -> Any:
    """DELETE request to Hub Protocol."""
    try:
        req = urllib.request.Request(_hub_url(path), headers=_headers(), method="DELETE")
        with urllib.request.urlopen(req, timeout=10) as resp:
            return json.loads(resp.read())
    except (urllib.error.URLError, Exception):
        return None


# ---------------------------------------------------------------------------
# Module-level response helpers
# ---------------------------------------------------------------------------

def _ok(data: Any) -> dict:
    return {"status": "done", "data": data}


def _err(message: str) -> dict:
    return {"status": "error", "message": message}


def _write_result(result: Any) -> dict:
    """Normalize a Hub Protocol write response.

    Returns _ok() on success, or pending_approval dict when the backend
    created a proposal instead of executing (granted=False). Agents should
    show the reviewUrl to the user and wait — never retry the same call.
    """
    if result is None:
        return _err("Hub Protocol request failed — check HUB_BASE_URL and SYNAP_API_KEY")
    if isinstance(result, dict) and result.get("granted") is False:
        return {
            "status": "pending_approval",
            "proposalId": result.get("proposalId"),
            "summary": result.get("summary", "Action requires human approval"),
            "reasoning": result.get("reasoning", ""),
            "reviewPath": result.get("reviewPath", ""),
            "reviewUrl": result.get("reviewUrl", ""),
            "message": f"This action needs approval. Review at: {result.get('reviewUrl', result.get('reviewPath', ''))}",
        }
    return _ok(result)


# ---------------------------------------------------------------------------
# Module-level tool schemas (22 tools)
# ---------------------------------------------------------------------------

TOOL_SCHEMAS = [
    # -- Discovery ------------------------------------------------------------
    {
        "name": "synap_orient",
        "description": (
            "Bootstrap context: fetch your identity, accessible workspaces, and available entity types "
            "(profiles). Call this first in any new session to orient yourself. Returns me (userId, scopes), "
            "workspaces list, and profiles list."
        ),
        "parameters": {
            "type": "object",
            "properties": {},
            "required": [],
        },
    },
    {
        "name": "synap_governance",
        "description": (
            "Check what actions auto-approve vs require human review in a workspace. Also returns pending "
            "proposals awaiting approval. Use before write operations to understand the approval policy."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "workspaceId": {"type": "string", "description": "Workspace ID to check governance for"},
            },
            "required": ["workspaceId"],
        },
    },
    # -- Entities -------------------------------------------------------------
    {
        "name": "synap_entity_create",
        "description": (
            "Create a new entity of any type (task, note, person, company, event, contact, deal, project, "
            "bookmark, capture, file, or any custom profile). Returns the created entity or a pending_approval "
            "if the workspace requires it."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "profileSlug": {
                    "type": "string",
                    "description": (
                        "Entity type: task, note, person, company, event, contact, deal, project, bookmark, "
                        "capture, file, anchor, or a custom slug"
                    ),
                },
                "name": {"type": "string", "description": "Display name for the entity"},
                "properties": {
                    "type": "object",
                    "description": (
                        "Profile-specific properties. For task: status (todo/in-progress/done/cancelled), "
                        "priority (low/medium/high), dueDate. For person: email, phone. "
                        "For deal: stage, value, closeDate."
                    ),
                },
                "workspaceId": {
                    "type": "string",
                    "description": (
                        "Target workspace ID. Omit for pod-wide profiles "
                        "(task, note, person, company, event, contact, bookmark, website, article)."
                    ),
                },
                "idempotencyKey": {
                    "type": "string",
                    "description": (
                        "Optional dedup key — same key within 24h returns the existing entity "
                        "instead of creating a duplicate."
                    ),
                },
            },
            "required": ["profileSlug", "name"],
        },
    },
    {
        "name": "synap_entity_get",
        "description": (
            "Fetch a single entity by ID, including its properties and optionally its direct connections "
            "(relations to other entities)."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "entityId": {"type": "string", "description": "Entity UUID"},
                "includeConnections": {
                    "type": "boolean",
                    "description": "If true, also fetches direct relations to other entities",
                    "default": False,
                },
            },
            "required": ["entityId"],
        },
    },
    {
        "name": "synap_entity_update",
        "description": (
            "Update an entity's properties (merge patch — only specified keys are changed, others preserved). "
            "May require approval in some workspaces."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "entityId": {"type": "string", "description": "Entity UUID"},
                "name": {"type": "string", "description": "New display name (optional)"},
                "properties": {
                    "type": "object",
                    "description": (
                        "Properties to update (merged with existing). "
                        "E.g. { status: 'done' } to close a task."
                    ),
                },
            },
            "required": ["entityId"],
        },
    },
    {
        "name": "synap_entity_search",
        "description": (
            "Search or list entities. Use q for full-text search, profileSlug to filter by type, "
            "workspaceId to scope to a workspace."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "q": {"type": "string", "description": "Full-text search query (optional — omit to list all)"},
                "profileSlug": {"type": "string", "description": "Filter by entity type (task, note, person, etc.)"},
                "workspaceId": {"type": "string", "description": "Scope to a specific workspace"},
                "limit": {"type": "integer", "description": "Max results (default 20, max 100)", "default": 20},
            },
            "required": [],
        },
    },
    # -- Relations ------------------------------------------------------------
    {
        "name": "synap_relation_create",
        "description": (
            "Create a typed directional link between two entities "
            "(e.g. task to project, person to company, deal to contact). Builds the knowledge graph."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "fromEntityId": {"type": "string", "description": "Source entity ID"},
                "toEntityId": {"type": "string", "description": "Target entity ID"},
                "type": {
                    "type": "string",
                    "description": (
                        "Relation type: belongs_to, assigned_to, created_by, related_to, "
                        "depends_on, mentions, part_of, or any custom type"
                    ),
                },
                "workspaceId": {
                    "type": "string",
                    "description": "Workspace context (optional for pod-wide entities)",
                },
            },
            "required": ["fromEntityId", "toEntityId", "type"],
        },
    },
    {
        "name": "synap_relation_list",
        "description": (
            "List relations for an entity, or traverse the knowledge graph from a starting entity "
            "up to 3 hops deep."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "entityId": {"type": "string", "description": "Entity to list relations for"},
                "type": {"type": "string", "description": "Filter by relation type (optional)"},
                "traverse": {
                    "type": "boolean",
                    "description": "If true, do BFS traversal up to maxDepth hops",
                    "default": False,
                },
                "maxDepth": {"type": "integer", "description": "BFS depth (1-3, default 2)", "default": 2},
            },
            "required": ["entityId"],
        },
    },
    # -- Memory ---------------------------------------------------------------
    {
        "name": "synap_remember",
        "description": (
            "Explicitly store a high-confidence fact or piece of knowledge in the user's long-term memory. "
            "Use for things the user wants permanently remembered across sessions. "
            "Different from sync_turn (which auto-records conversation). "
            "Confidence 1.0 = explicitly stated, 0.7-0.9 = inferred."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "fact": {
                    "type": "string",
                    "description": (
                        "The fact to store, in clear language. "
                        "E.g. 'Antoine prefers async communication' or 'Project X deadline is 2026-06-30'"
                    ),
                },
                "confidence": {
                    "type": "number",
                    "description": "Confidence 0-1 (default 1.0 for explicit facts)",
                    "default": 1.0,
                },
            },
            "required": ["fact"],
        },
    },
    {
        "name": "synap_recall",
        "description": (
            "Search the user's long-term memory for relevant facts. "
            "Uses semantic search when available, falls back to full-text. "
            "Use to answer questions about the user's preferences, history, or previously stored information."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "query": {"type": "string", "description": "What to search for in memory"},
                "limit": {"type": "integer", "description": "Max facts to return (default 10)", "default": 10},
            },
            "required": ["query"],
        },
    },
    # -- Knowledge ------------------------------------------------------------
    {
        "name": "synap_knowledge_read",
        "description": (
            "Read a procedural knowledge document by key (e.g. 'how-to/deploy', 'config/defaults') "
            "or search knowledge by query. Use for reference docs, runbooks, configuration guides."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string",
                    "description": (
                        "Exact knowledge key to fetch (URL-path style, e.g. 'project/architecture'). "
                        "Omit to search instead."
                    ),
                },
                "query": {"type": "string", "description": "Search query if key is not known"},
                "namespace": {"type": "string", "description": "Knowledge namespace filter (optional)"},
            },
            "required": [],
        },
    },
    {
        "name": "synap_knowledge_write",
        "description": (
            "Create or update a procedural knowledge document "
            "(runbook, config, architecture note, how-to guide). Stored under a key for later retrieval."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string",
                    "description": "Knowledge key (URL-path style, e.g. 'project/architecture')",
                },
                "content": {"type": "string", "description": "Markdown content of the knowledge document"},
                "namespace": {
                    "type": "string",
                    "description": "Namespace for organization (optional, e.g. 'team', 'personal', 'project')",
                },
            },
            "required": ["key", "content"],
        },
    },
    # -- Documents ------------------------------------------------------------
    {
        "name": "synap_document_create",
        "description": (
            "Create a long-form Markdown document "
            "(report, summary, spec, meeting notes, etc.) optionally linked to an entity."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "title": {"type": "string", "description": "Document title"},
                "content": {"type": "string", "description": "Full Markdown content"},
                "entityId": {"type": "string", "description": "Link document to an entity (optional)"},
                "workspaceId": {"type": "string", "description": "Workspace context (optional)"},
                "idempotencyKey": {"type": "string", "description": "Dedup key (optional)"},
            },
            "required": ["title", "content"],
        },
    },
    {
        "name": "synap_document_read",
        "description": "Fetch a document by ID including its full Markdown content.",
        "parameters": {
            "type": "object",
            "properties": {
                "documentId": {"type": "string", "description": "Document UUID"},
            },
            "required": ["documentId"],
        },
    },
    # -- Capture --------------------------------------------------------------
    {
        "name": "synap_capture",
        "description": (
            "Parse unstructured text (message, URL, note, paste) into structured entity proposals. "
            "The AI extracts entities, properties, and relationships. "
            "Returns proposals to create — call synap_entity_create to execute them."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string",
                    "description": "Unstructured text to structure (message content, URL, pasted text, etc.)",
                },
                "profileSlug": {
                    "type": "string",
                    "description": "Hint for target entity type (optional — AI will infer if omitted)",
                },
            },
            "required": ["text"],
        },
    },
    # -- Workspace & Structure ------------------------------------------------
    {
        "name": "synap_workspace_create",
        "description": (
            "Provision a new workspace from a definition (profiles, views, seed entities). "
            "Use to set up a new space for a project, team, or use-case."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "name": {"type": "string", "description": "Workspace display name"},
                "definition": {
                    "type": "object",
                    "description": (
                        "Workspace definition with profiles, views, and seed entities "
                        "(optional — creates blank workspace if omitted)"
                    ),
                },
            },
            "required": ["name"],
        },
    },
    {
        "name": "synap_view_create",
        "description": (
            "Create a view (table, kanban, list, grid, gallery, calendar, bento dashboard, etc.) "
            "over a set of entities in a workspace."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "name": {"type": "string", "description": "View display name"},
                "type": {
                    "type": "string",
                    "description": (
                        "View type: table, kanban, list, grid, gallery, calendar, bento, "
                        "matrix, masonry, flow, branch_tree, whiteboard"
                    ),
                },
                "workspaceId": {"type": "string", "description": "Workspace to create view in"},
                "profileId": {"type": "string", "description": "Entity profile this view shows (optional)"},
                "config": {
                    "type": "object",
                    "description": "View-specific configuration (columns, groupBy, filters, etc.)",
                },
            },
            "required": ["name", "type", "workspaceId"],
        },
    },
    # -- Channels & Messaging -------------------------------------------------
    {
        "name": "synap_channel_get",
        "description": (
            "Get or create an AI channel. Use 'personal' to get the user's personal AI channel. "
            "Use contextObjectType+contextObjectId to get/create a channel scoped to a specific entity or document."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "mode": {
                    "type": "string",
                    "enum": ["personal", "by-context", "list"],
                    "description": (
                        "personal=user's personal channel; "
                        "by-context=channel for specific entity/doc; "
                        "list=all channels"
                    ),
                },
                "contextObjectType": {
                    "type": "string",
                    "description": "For by-context: 'entity' or 'document'",
                },
                "contextObjectId": {
                    "type": "string",
                    "description": "For by-context: entity or document ID",
                },
                "workspaceId": {"type": "string", "description": "Workspace context"},
            },
            "required": ["mode"],
        },
    },
    {
        "name": "synap_channel_message",
        "description": (
            "Post a message to a channel or thread, or trigger an AI response in a channel."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "channelId": {"type": "string", "description": "Target channel ID"},
                "threadId": {
                    "type": "string",
                    "description": (
                        "Target thread ID (if posting to a specific thread instead of channel)"
                    ),
                },
                "content": {"type": "string", "description": "Message content (Markdown supported)"},
                "role": {
                    "type": "string",
                    "enum": ["user", "assistant"],
                    "description": "Message author role",
                    "default": "assistant",
                },
                "triggerAI": {
                    "type": "boolean",
                    "description": "If true, trigger an AI response after posting",
                    "default": False,
                },
            },
            "required": ["content"],
        },
    },
    # -- Search ---------------------------------------------------------------
    {
        "name": "synap_search",
        "description": (
            "Cross-collection full-text search across entities, documents, views, and projects in a workspace. "
            "Use when you don't know which collection contains the information."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "q": {"type": "string", "description": "Search query"},
                "workspaceId": {"type": "string", "description": "Scope to workspace (optional)"},
                "collections": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": (
                        "Limit to specific collections: entities, documents, views, projects, agents (optional)"
                    ),
                },
            },
            "required": ["q"],
        },
    },
    # -- Governance -----------------------------------------------------------
    {
        "name": "synap_proposal_list",
        "description": (
            "List pending proposals in a workspace that are awaiting human review and approval. "
            "Use to check if previous actions are still pending."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "workspaceId": {
                    "type": "string",
                    "description": "Workspace to check (optional — all workspaces if omitted)",
                },
                "status": {
                    "type": "string",
                    "enum": ["pending", "approved", "rejected", "all"],
                    "description": "Filter by status (default: pending)",
                    "default": "pending",
                },
            },
            "required": [],
        },
    },
    {
        "name": "synap_proposal_revise",
        "description": (
            "Revise a pending proposal after the user provides feedback. "
            "Use when the user says 'change X to Y' about a proposal that's waiting for approval."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "proposalId": {"type": "string", "description": "Proposal UUID to revise"},
                "summary": {"type": "string", "description": "Updated summary of what the proposal does"},
                "reasoning": {"type": "string", "description": "Updated reasoning / justification"},
            },
            "required": ["proposalId"],
        },
    },
]


class SynapMemoryProvider:
    """Synap Data Pod — Hermes MemoryProvider contract."""

    def __init__(self):
        self._session_id: str | None = None

    def is_available(self) -> bool:
        return bool(os.environ.get("SYNAP_API_KEY")) and bool(os.environ.get("HUB_BASE_URL"))

    def initialize(self, session_id: str, **kwargs) -> None:
        self._session_id = session_id

    def _embed(self, text: str) -> list[float] | None:
        """Get a 1536-d embedding via the Hermes internal gateway.

        Calls http://127.0.0.1:8642/v1/embeddings (OpenAI-compat) using
        the model set in SYNAP_EMBED_MODEL. Returns None when the model
        is unset, unavailable, or returns a non-1536-d vector — callers
        degrade to full-text search without interrupting the session.

        The 1536-d constraint matches the knowledge_facts pgvector column.
        Ollama embedding models (768-1024-d) are intentionally excluded.
        """
        model = os.environ.get("SYNAP_EMBED_MODEL", "")
        if not model:
            return None
        try:
            payload = json.dumps({"model": model, "input": text}).encode()
            key = os.environ.get("API_SERVER_KEY", "")
            req = urllib.request.Request(
                "http://127.0.0.1:8642/v1/embeddings",
                data=payload,
                headers={"Content-Type": "application/json", "Authorization": f"Bearer {key}"},
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=5) as resp:
                body = json.loads(resp.read())
                vec = body["data"][0]["embedding"]
                if isinstance(vec, list) and len(vec) == 1536:
                    return vec
        except Exception:
            pass
        return None

    def prefetch(self, query: str) -> list[dict]:
        """Return relevant memories for the given query.

        Prefers semantic search (POST /memory/search with pgvector) when
        SYNAP_EMBED_MODEL is set and the gateway returns a valid 1536-d
        embedding. Falls back to full-text (GET /memory?query=) otherwise.
        """
        if not query:
            return []
        # Semantic path — try embedding via Hermes gateway
        embedding = self._embed(query)
        if embedding:
            results = _post("/memory/search", {"embedding": embedding, "limit": 10})
            if isinstance(results, list) and results:
                return results
        # Full-text fallback
        results = _get("/memory", {"query": query, "limit": "10"})
        if isinstance(results, list):
            return results
        return []

    def sync_turn(self, user: str, assistant: str) -> None:
        """Persist a conversation turn as two memory facts.

        Includes embeddings when SYNAP_EMBED_MODEL is set so facts are
        discoverable via semantic search in future prefetch() calls.
        """
        session_tag = f"[session:{self._session_id}]" if self._session_id else ""
        if user:
            fact = f"{session_tag}[user] {user}"
            payload: dict = {"fact": fact}
            emb = self._embed(fact)
            if emb:
                payload["embedding"] = emb
            _post("/memory", payload)
        if assistant:
            fact = f"{session_tag}[assistant] {assistant}"
            payload = {"fact": fact}
            emb = self._embed(fact)
            if emb:
                payload["embedding"] = emb
            _post("/memory", payload)

    def on_session_end(self, messages: list[dict]) -> None:
        """Summarise the session as a single memory fact with embedding."""
        if not messages:
            return
        parts = []
        for m in messages[-20:]:  # cap at last 20 to avoid huge facts
            role = m.get("role", "?")
            content = str(m.get("content", ""))[:300]
            parts.append(f"{role}: {content}")
        summary = " | ".join(parts)
        session_tag = f"[session:{self._session_id}] " if self._session_id else ""
        fact = f"{session_tag}[summary] {summary}"
        payload: dict = {"fact": fact, "confidence": 0.9}
        emb = self._embed(fact)
        if emb:
            payload["embedding"] = emb
        _post("/memory", payload)

    def on_memory_write(self, action: str, target: str, content: str) -> None:
        """Intercept explicit remember/update commands — store as high-confidence facts."""
        if action in ("remember", "add", "update", "replace"):
            payload: dict = {"fact": content, "confidence": 1.0}
            emb = self._embed(content)
            if emb:
                payload["embedding"] = emb
            _post("/memory", payload)

    # -------------------------------------------------------------------------
    # Tool suite
    # -------------------------------------------------------------------------

    def get_tool_schemas(self) -> list[dict]:
        return TOOL_SCHEMAS

    def handle_tool_call(self, name: str, args: dict) -> Any:
        handlers = {
            "synap_orient":           self._tool_orient,
            "synap_governance":       self._tool_governance,
            "synap_entity_create":    self._tool_entity_create,
            "synap_entity_get":       self._tool_entity_get,
            "synap_entity_update":    self._tool_entity_update,
            "synap_entity_search":    self._tool_entity_search,
            "synap_relation_create":  self._tool_relation_create,
            "synap_relation_list":    self._tool_relation_list,
            "synap_remember":         self._tool_remember,
            "synap_recall":           self._tool_recall,
            "synap_knowledge_read":   self._tool_knowledge_read,
            "synap_knowledge_write":  self._tool_knowledge_write,
            "synap_document_create":  self._tool_document_create,
            "synap_document_read":    self._tool_document_read,
            "synap_capture":          self._tool_capture,
            "synap_workspace_create": self._tool_workspace_create,
            "synap_view_create":      self._tool_view_create,
            "synap_channel_get":      self._tool_channel_get,
            "synap_channel_message":  self._tool_channel_message,
            "synap_search":           self._tool_search,
            "synap_proposal_list":    self._tool_proposal_list,
            "synap_proposal_revise":  self._tool_proposal_revise,
        }
        handler = handlers.get(name)
        if handler is None:
            return _err(f"Unknown tool: {name}")
        try:
            return handler(args)
        except Exception as e:
            return _err(str(e))

    # -- Discovery ------------------------------------------------------------

    def _tool_orient(self, args: dict) -> dict:
        me = _get("/users/me")
        workspaces = _get("/workspaces")
        profiles = _get("/profiles")
        return _ok({"me": me, "workspaces": workspaces or [], "profiles": profiles or []})

    def _tool_governance(self, args: dict) -> dict:
        ws_id = args.get("workspaceId", "")
        gov = _get(f"/workspaces/{ws_id}/governance")
        proposals = _get("/proposals", {"workspaceId": ws_id, "status": "pending"})
        return _ok({"governance": gov, "pendingProposals": proposals or []})

    # -- Entities -------------------------------------------------------------

    def _tool_entity_create(self, args: dict) -> dict:
        payload: dict = {
            "profileSlug": args["profileSlug"],
            "name": args["name"],
        }
        if args.get("properties"):
            payload["properties"] = args["properties"]
        if args.get("workspaceId"):
            payload["workspaceId"] = args["workspaceId"]
        if args.get("idempotencyKey"):
            payload["idempotencyKey"] = args["idempotencyKey"]
        return _write_result(_post("/entities", payload))

    def _tool_entity_get(self, args: dict) -> dict:
        entity = _get(f"/entities/{args['entityId']}")
        if entity is None:
            return _err("Entity not found")
        if args.get("includeConnections"):
            connections = _get(f"/entities/{args['entityId']}/connections")
            entity["connections"] = connections or []
        return _ok(entity)

    def _tool_entity_update(self, args: dict) -> dict:
        payload: dict = {}
        if args.get("name"):
            payload["name"] = args["name"]
        if args.get("properties"):
            payload["properties"] = args["properties"]
        result = _put(f"/entities/{args['entityId']}", payload)
        return _write_result(result)

    def _tool_entity_search(self, args: dict) -> dict:
        params: dict = {}
        if args.get("q"):
            params["q"] = args["q"]
        if args.get("profileSlug"):
            params["profileSlug"] = args["profileSlug"]
        if args.get("workspaceId"):
            params["workspaceId"] = args["workspaceId"]
        params["limit"] = str(args.get("limit", 20))
        result = _get("/entities", params)
        return _ok(result or [])

    # -- Relations ------------------------------------------------------------

    def _tool_relation_create(self, args: dict) -> dict:
        payload: dict = {
            "fromEntityId": args["fromEntityId"],
            "toEntityId": args["toEntityId"],
            "type": args["type"],
        }
        if args.get("workspaceId"):
            payload["workspaceId"] = args["workspaceId"]
        return _write_result(_post("/relations", payload))

    def _tool_relation_list(self, args: dict) -> dict:
        entity_id = args["entityId"]
        if args.get("traverse"):
            params: dict = {
                "startEntityId": entity_id,
                "maxDepth": str(args.get("maxDepth", 2)),
            }
            result = _get("/graph/traverse", params)
        else:
            params = {"entityId": entity_id}
            if args.get("type"):
                params["type"] = args["type"]
            result = _get("/relations", params)
        return _ok(result or [])

    # -- Memory ---------------------------------------------------------------

    def _tool_remember(self, args: dict) -> dict:
        payload: dict = {
            "fact": args["fact"],
            "confidence": args.get("confidence", 1.0),
        }
        emb = self._embed(args["fact"])
        if emb:
            payload["embedding"] = emb
        return _write_result(_post("/memory", payload))

    def _tool_recall(self, args: dict) -> dict:
        query = args["query"]
        limit = args.get("limit", 10)
        # Try semantic first
        emb = self._embed(query)
        if emb:
            results = _post("/memory/search", {"embedding": emb, "limit": limit})
            if isinstance(results, list) and results:
                return _ok(results)
        # Full-text fallback
        results = _get("/memory", {"query": query, "limit": str(limit)})
        return _ok(results or [])

    # -- Knowledge ------------------------------------------------------------

    def _tool_knowledge_read(self, args: dict) -> dict:
        if args.get("key"):
            key = urllib.parse.quote(args["key"], safe="")
            result = _get(f"/knowledge/{key}")
        else:
            params: dict = {}
            if args.get("query"):
                params["q"] = args["query"]
            if args.get("namespace"):
                params["namespace"] = args["namespace"]
            result = _get("/knowledge/search", params)
        if result is None:
            return _err("Knowledge entry not found")
        return _ok(result)

    def _tool_knowledge_write(self, args: dict) -> dict:
        key = urllib.parse.quote(args["key"], safe="")
        payload: dict = {"content": args["content"]}
        if args.get("namespace"):
            payload["namespace"] = args["namespace"]
        return _write_result(_put(f"/knowledge/{key}", payload))

    # -- Documents ------------------------------------------------------------

    def _tool_document_create(self, args: dict) -> dict:
        payload: dict = {
            "title": args["title"],
            "content": args["content"],
        }
        if args.get("entityId"):
            payload["entityId"] = args["entityId"]
        if args.get("workspaceId"):
            payload["workspaceId"] = args["workspaceId"]
        if args.get("idempotencyKey"):
            payload["idempotencyKey"] = args["idempotencyKey"]
        return _write_result(_post("/documents", payload))

    def _tool_document_read(self, args: dict) -> dict:
        result = _get(f"/documents/{args['documentId']}")
        if result is None:
            return _err("Document not found")
        return _ok(result)

    # -- Capture --------------------------------------------------------------

    def _tool_capture(self, args: dict) -> dict:
        payload: dict = {"text": args["text"]}
        if args.get("profileSlug"):
            payload["profileSlug"] = args["profileSlug"]
        result = _post("/capture/structure", payload)
        return _ok(result) if result else _err("Capture structure failed")

    # -- Workspace & Structure ------------------------------------------------

    def _tool_workspace_create(self, args: dict) -> dict:
        payload: dict = {"name": args["name"]}
        if args.get("definition"):
            payload["definition"] = args["definition"]
        return _write_result(_post("/workspaces/from-definition", payload))

    def _tool_view_create(self, args: dict) -> dict:
        payload: dict = {
            "name": args["name"],
            "type": args["type"],
            "workspaceId": args["workspaceId"],
        }
        if args.get("profileId"):
            payload["profileId"] = args["profileId"]
        if args.get("config"):
            payload["config"] = args["config"]
        return _write_result(_post("/views", payload))

    # -- Channels & Messaging -------------------------------------------------

    def _tool_channel_get(self, args: dict) -> dict:
        mode = args.get("mode", "personal")
        if mode == "personal":
            result = _get("/channels/personal")
        elif mode == "by-context":
            payload: dict = {
                "contextObjectType": args.get("contextObjectType", "entity"),
                "contextObjectId": args.get("contextObjectId", ""),
            }
            if args.get("workspaceId"):
                payload["workspaceId"] = args["workspaceId"]
            result = _post("/channels/by-context", payload)
        else:
            params: dict = {}
            if args.get("workspaceId"):
                params["workspaceId"] = args["workspaceId"]
            result = _get("/channels", params)
        return _ok(result) if result else _err("Channel not found")

    def _tool_channel_message(self, args: dict) -> dict:
        content = args["content"]
        role = args.get("role", "assistant")
        if args.get("threadId"):
            payload: dict = {"content": content, "role": role}
            result = _post(f"/threads/{args['threadId']}/messages", payload)
        elif args.get("channelId") and args.get("triggerAI"):
            payload = {"channelId": args["channelId"], "message": content}
            result = _post("/channels/trigger-ai", payload)
        elif args.get("channelId"):
            # Create thread in channel then post
            thread = _post("/threads", {"channelId": args["channelId"]})
            thread_id = thread.get("id") if isinstance(thread, dict) else None
            if not thread_id:
                return _err("Could not create thread in channel")
            result = _post(f"/threads/{thread_id}/messages", {"content": content, "role": role})
        else:
            return _err("Either channelId or threadId is required")
        return _write_result(result)

    # -- Search ---------------------------------------------------------------

    def _tool_search(self, args: dict) -> dict:
        params: dict = {"q": args["q"]}
        if args.get("workspaceId"):
            params["workspaceId"] = args["workspaceId"]
        if args.get("collections"):
            params["collections"] = ",".join(args["collections"])
        result = _get("/search", params)
        return _ok(result or [])

    # -- Governance -----------------------------------------------------------

    def _tool_proposal_list(self, args: dict) -> dict:
        params: dict = {"status": args.get("status", "pending")}
        if args.get("workspaceId"):
            params["workspaceId"] = args["workspaceId"]
        result = _get("/proposals", params)
        return _ok(result or [])

    def _tool_proposal_revise(self, args: dict) -> dict:
        payload: dict = {}
        if args.get("summary"):
            payload["summary"] = args["summary"]
        if args.get("reasoning"):
            payload["reasoning"] = args["reasoning"]
        result = _patch(f"/proposals/{args['proposalId']}", payload)
        return _ok(result) if result else _err("Proposal revision failed")


def register(ctx):
    ctx.register_memory_provider(SynapMemoryProvider())
`;

/**
 * Generates the Synap memory provider plugin into `~/.eve/hermes/plugins/memory/synap/`:
 *   - plugin.yaml  — Hermes plugin manifest
 *   - __init__.py  — MemoryProvider implementation (pure stdlib, no deps)
 *
 * The plugin dir is volume-mounted into the Hermes container at
 * $HERMES_HOME/plugins/memory/synap/ so the official image picks it up
 * without any custom Dockerfile.
 */
export function generateSynapPlugin(): { pluginDir: string } {
  const pluginDir = join(homedir(), '.eve', 'hermes', 'plugins', 'memory', 'synap');
  mkdirSync(pluginDir, { recursive: true });
  writeFileSync(join(pluginDir, 'plugin.yaml'), SYNAP_PLUGIN_YAML, 'utf-8');
  writeFileSync(join(pluginDir, '__init__.py'), SYNAP_PROVIDER_PY, 'utf-8');
  return { pluginDir };
}
