import { existsSync, mkdirSync, writeFileSync, copyFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { randomBytes } from 'node:crypto';
import type { EveSecrets } from './secrets-contract.js';
import { readAgentKeyOrLegacy, readEveSecrets, writeEveSecrets } from './secrets-contract.js';
import { resolveSynapUrl } from './components.js';

/** Default Hub Protocol path on the Synap API host (Better Auth / Hub REST). */
export const DEFAULT_HUB_PATH = '/api/hub';

export function resolveHubBaseUrl(secrets: EveSecrets | null): string | undefined {
  if (secrets?.synap?.hubBaseUrl?.trim()) {
    return secrets.synap.hubBaseUrl.replace(/\/$/, '');
  }
  const base = resolveSynapUrl(secrets).replace(/\/$/, '');
  if (!base) return undefined;
  return `${base}${DEFAULT_HUB_PATH}`;
}

export function defaultSkillsDir(): string {
  return join(homedir(), '.eve', 'skills');
}

/**
 * Fetches the bundled skill packages from the pod and writes them into
 * the local skills directory (~/.eve/skills/).
 *
 * If the pod is unreachable, falls back to the embedded stub so
 * Hermes / Claude Code always have at least a minimal Hub reference.
 *
 * Directory layout written:
 *   ~/.eve/skills/synap/SKILL.md            ← core data + memory + channels
 *   ~/.eve/skills/synap/governance.md
 *   ~/.eve/skills/synap/linking.md
 *   ~/.eve/skills/synap/capture.md
 *   ~/.eve/skills/synap-schema/SKILL.md     ← profiles + property defs
 *   ~/.eve/skills/synap-schema/property-types.md
 *   ~/.eve/skills/synap-ui/SKILL.md         ← views + dashboards
 */
export async function ensureEveSkillsLayout(
  skillsDir: string = defaultSkillsDir(),
  hubBaseUrl?: string,
  apiKey?: string,
): Promise<void> {
  // Always ensure the synap dir exists as a fallback
  mkdirSync(join(skillsDir, 'synap'), { recursive: true });

  if (hubBaseUrl && apiKey) {
    try {
      const res = await fetch(`${hubBaseUrl}/skills/system`, {
        headers: { Authorization: `Bearer ${apiKey}` },
        signal: AbortSignal.timeout(8000),
      });
      if (res.ok) {
        const packages = await res.json() as Array<{
          slug: string;
          files: Array<{ path: string; content: string }>;
        }>;
        for (const pkg of packages) {
          const pkgDir = join(skillsDir, pkg.slug);
          mkdirSync(pkgDir, { recursive: true });
          for (const file of pkg.files) {
            writeFileSync(join(pkgDir, file.path), file.content, 'utf-8');
          }
        }
        return;
      }
    } catch {
      // pod unreachable — fall through to stub
    }
  }

  // Fallback stub: minimal Hub Protocol reference
  const stubPath = join(skillsDir, 'synap', 'SKILL.md');
  if (!existsSync(stubPath)) {
    writeFileSync(stubPath, `---
name: synap
description: Use for memory, entities, channels, search, and governance via the Synap Hub Protocol.
---

# Synap Hub Protocol

Base URL: $HUB_BASE_URL
Auth: Authorization: Bearer $SYNAP_API_KEY

Key endpoints:
  GET  /memory?query=...          full-text search facts
  POST /memory                    store a fact
  GET  /entities/search?q=...     search entities
  POST /entities                  create entity
  GET  /entities/:id
  PUT  /entities/:id              update entity (merges)
  GET  /channels?workspaceId=...  list channels
  POST /skills/:id/execute        run a user skill
  GET  /skills/system             list system skill docs
  GET  /profiles                  list entity types

Run GET /users/me + GET /workspaces on startup to orient yourself.
`, 'utf-8');
  }
}

/**
 * Dotenv for OpenCode / sandbox / any tool that reads `.env` in the project root.
 *
 * Uses the `coder` agent's key — one Hub identity for the local AI
 * coder regardless of which engine binary is selected via
 * `secrets.builder.codeEngine`. Falls back to the legacy single key
 * for installs that haven't migrated yet.
 */
export async function writeBuilderProjectEnv(projectDir: string, cwd: string = process.cwd()): Promise<void> {
  const secrets = await readEveSecrets(cwd);
  const hub = resolveHubBaseUrl(secrets);
  const skillsDir = secrets?.builder?.skillsDir ?? defaultSkillsDir();
  const synapApiKeyForSkills = await readAgentKeyOrLegacy('coder', cwd);
  await ensureEveSkillsLayout(skillsDir, hub, synapApiKeyForSkills);

  const synapApiKey = await readAgentKeyOrLegacy('coder', cwd);

  const lines: string[] = [
    '# Generated by Eve — Synap Hub + workspace wiring',
    `SYNAP_API_URL=${resolveSynapUrl(secrets)}`,
    `SYNAP_API_KEY=${synapApiKey}`,
    `HUB_BASE_URL=${hub ?? ''}`,
    `EVE_SKILLS_DIR=${skillsDir}`,
    `DOKPLOY_WEBHOOK_URL=${secrets?.builder?.dokployWebhookUrl ?? process.env.DOKPLOY_WEBHOOK_URL ?? ''}`,
    `DOKPLOY_API_URL=${secrets?.builder?.dokployApiUrl ?? ''}`,
    `DOKPLOY_API_KEY=${secrets?.builder?.dokployApiKey ?? ''}`,
    '',
  ];
  writeFileSync(join(projectDir, '.env'), lines.join('\n'), { mode: 0o600 });
}

/**
 * Writes `.eve/sandbox.env` for docker compose --env-file.
 *
 * The sandbox is a generic Eve work environment (no specific component
 * agent) — it uses the `eve` agent identity for Hub Protocol calls so
 * its activity attributes back to Eve itself. Falls back to legacy if
 * no per-agent eve key has been minted yet.
 */
export async function writeSandboxEnvFile(cwd: string = process.cwd()): Promise<string> {
  const secrets = await readEveSecrets(cwd);
  const hub = resolveHubBaseUrl(secrets);
  const skillsDir = secrets?.builder?.skillsDir ?? defaultSkillsDir();
  const workspaceDir = secrets?.builder?.workspaceDir ?? join(cwd, '.eve', 'workspace');
  const synapApiKeyForSkills = await readAgentKeyOrLegacy('eve', cwd);
  await ensureEveSkillsLayout(skillsDir, hub, synapApiKeyForSkills);

  const synapApiKey = await readAgentKeyOrLegacy('eve', cwd);

  const eveDir = join(cwd, '.eve');
  mkdirSync(eveDir, { recursive: true });
  const path = join(eveDir, 'sandbox.env');
  const lines = [
    `SYNAP_API_URL=${resolveSynapUrl(secrets)}`,
    `SYNAP_API_KEY=${synapApiKey}`,
    `HUB_BASE_URL=${hub ?? ''}`,
    `EVE_SKILLS_DIR=${skillsDir}`,
    `EVE_WORKSPACE_DIR=${workspaceDir}`,
    `DOKPLOY_WEBHOOK_URL=${secrets?.builder?.dokployWebhookUrl ?? process.env.DOKPLOY_WEBHOOK_URL ?? ''}`,
  ];
  writeFileSync(path, lines.join('\n') + '\n', { mode: 0o600 });
  return path;
}

/**
 * Claude Code loads skills from `<project>/.claude/skills/<name>/SKILL.md`.
 * Copies all Synap skill packages (synap, synap-schema, synap-ui) into the project.
 * Call after ensureEveSkillsLayout() has already written files to skillsDir.
 */
export function copySynapSkillIntoClaudeProject(projectDir: string, skillsDir: string = defaultSkillsDir()): void {
  const { readdirSync: _readdirSync, statSync: _statSync } = require('node:fs') as typeof import('node:fs');
  const skillPkgs = ['synap', 'synap-schema', 'synap-ui'];
  for (const pkg of skillPkgs) {
    const srcDir = join(skillsDir, pkg);
    const destDir = join(projectDir, '.claude', 'skills', pkg);
    try {
      const files = _readdirSync(srcDir);
      mkdirSync(destDir, { recursive: true });
      for (const file of files) {
        if (file.endsWith('.md')) {
          copyFileSync(join(srcDir, file), join(destDir, file));
        }
      }
    } catch {
      // skill package not yet fetched — skip silently
    }
  }
}

/**
 * Claude Code `settings.json` env block (see https://code.claude.com/docs/en/settings ).
 *
 * Uses the unified `coder` agent's Hub key — one identity for the local
 * AI coder regardless of which engine binary is selected via
 * `secrets.builder.codeEngine`. Falls back to the legacy single key for
 * installs that haven't migrated yet.
 */
export async function writeClaudeCodeSettings(projectDir: string, cwd: string = process.cwd()): Promise<void> {
  const secrets = await readEveSecrets(cwd);
  const hub = resolveHubBaseUrl(secrets);
  const synapApiKey = await readAgentKeyOrLegacy('coder', cwd);
  const skillsDir = secrets?.builder?.skillsDir ?? defaultSkillsDir();
  const dir = join(projectDir, '.claude');
  mkdirSync(dir, { recursive: true });

  const settings = {
    env: {
      SYNAP_API_URL: resolveSynapUrl(secrets),
      SYNAP_API_KEY: synapApiKey,
      HUB_BASE_URL: hub ?? '',
      EVE_SKILLS_DIR: skillsDir,
    },
  };
  writeFileSync(join(dir, 'settings.json'), JSON.stringify(settings, null, 2), 'utf-8');

  // If Hermes is installed, register its MCP server so Claude Code can call Hermes tools
  const hermesApiKey = secrets?.builder?.hermes?.apiServerKey;
  if (hermesApiKey) {
    const mcpServersDir = join(dir, 'mcp-servers');
    mkdirSync(mcpServersDir, { recursive: true });
    const hermesMcp = {
      type: 'http',
      url: 'http://localhost:9120',
      name: 'hermes',
      description: 'Hermes agent — memory, channels, skills via Synap Hub Protocol',
      headers: { Authorization: `Bearer ${hermesApiKey}` },
    };
    writeFileSync(join(mcpServersDir, 'hermes.json'), JSON.stringify(hermesMcp, null, 2), 'utf-8');
  }
}

/**
 * Dotenv for Hermes daemon — reads secrets and writes `~/.eve/hermes.env`
 * for docker compose `env_file`. Injects Hub credentials, AI config, and
 * centralised channel tokens so Hermes can serve Telegram/Discord/etc without
 * storing its own copy of the credentials.
 *
 * Channel routing: `secrets.channelRouting` maps platform → agent-slug. If the
 * target agent is `hermes` (or no routing entry exists), channel env vars are
 * injected. This keeps Hermes stateless relative to channel credentials while
 * remaining trivially swappable — change the routing entry and re-run to
 * redirect a platform to another agent without touching Hermes config.
 */
export async function writeHermesEnvFile(cwd: string = process.cwd()): Promise<string> {
  const secrets = await readEveSecrets(cwd);
  const hub = resolveHubBaseUrl(secrets);
  const hermesConfig = secrets?.builder?.hermes;
  const synapApiKey = await readAgentKeyOrLegacy('hermes', cwd);

  // Ensure a stable API_SERVER_KEY exists — generated once at first write,
  // then reused so OpenWebUI (and other consumers) don't need reconfiguring.
  let apiServerKey = hermesConfig?.apiServerKey;
  if (!apiServerKey) {
    apiServerKey = randomBytes(32).toString('hex');
    await writeEveSecrets({
      builder: { hermes: { ...(hermesConfig ?? {}), apiServerKey } },
    });
  }

  const eveDir = join(cwd, '.eve');
  mkdirSync(eveDir, { recursive: true });
  const path = join(eveDir, 'hermes.env');

  const lines: string[] = [
    `SYNAP_API_URL=${resolveSynapUrl(secrets)}`,
    `SYNAP_API_KEY=${synapApiKey}`,
    `HUB_BASE_URL=${hub ?? ''}`,
    `HERMES_ENABLED=${hermesConfig?.enabled ?? true}`,
    `HERMES_POLL_INTERVAL_MS=${hermesConfig?.pollIntervalMs ?? 30000}`,
    `HERMES_MAX_CONCURRENT_TASKS=${hermesConfig?.maxConcurrentTasks ?? 1}`,
    `EVE_WORKSPACE_DIR=${secrets?.builder?.workspaceDir ?? join(cwd, '.eve', 'workspace')}`,
    // API server key — clients (OpenWebUI, LobeChat, etc.) use this to call
    // the Hermes OpenAI-compat gateway at port 8642.
    `API_SERVER_ENABLED=true`,
    `API_SERVER_PORT=8642`,
    `API_SERVER_KEY=${apiServerKey}`,
  ];

  // Inject centralised channel credentials for each platform routed to hermes
  // (or defaulting to hermes when no routing entry is set).
  const routing = secrets?.channels ? buildChannelRouting(secrets) : {};
  const channels = secrets?.channels ?? {};

  if (channels.telegram?.enabled && routing.telegram === 'hermes') {
    lines.push(`TELEGRAM_BOT_TOKEN=${channels.telegram.botToken ?? ''}`);
    if (channels.telegram.webhookSecret) {
      lines.push(`TELEGRAM_WEBHOOK_SECRET=${channels.telegram.webhookSecret}`);
    }
  }
  if (channels.discord?.enabled && routing.discord === 'hermes') {
    lines.push(`DISCORD_BOT_TOKEN=${channels.discord.botToken ?? ''}`);
    if (channels.discord.guildId) lines.push(`DISCORD_GUILD_ID=${channels.discord.guildId}`);
    if (channels.discord.applicationId) lines.push(`DISCORD_APPLICATION_ID=${channels.discord.applicationId}`);
  }
  if (channels.whatsapp?.enabled && routing.whatsapp === 'hermes') {
    lines.push(`WHATSAPP_PHONE_NUMBER_ID=${channels.whatsapp.phoneNumberId ?? ''}`);
    lines.push(`WHATSAPP_ACCESS_TOKEN=${channels.whatsapp.accessToken ?? ''}`);
    if (channels.whatsapp.verifyToken) lines.push(`WHATSAPP_VERIFY_TOKEN=${channels.whatsapp.verifyToken}`);
  }
  if (channels.signal?.enabled && routing.signal === 'hermes') {
    lines.push(`SIGNAL_PHONE_NUMBER=${channels.signal.phoneNumber ?? ''}`);
    lines.push(`SIGNAL_API_URL=${channels.signal.apiUrl ?? ''}`);
  }
  if (channels.matrix?.enabled && routing.matrix === 'hermes') {
    lines.push(`MATRIX_HOMESERVER_URL=${channels.matrix.homeserverUrl ?? ''}`);
    lines.push(`MATRIX_ACCESS_TOKEN=${channels.matrix.accessToken ?? ''}`);
    if (channels.matrix.roomId) lines.push(`MATRIX_ROOM_ID=${channels.matrix.roomId}`);
  }
  if (channels.slack?.enabled && routing.slack === 'hermes') {
    lines.push(`SLACK_BOT_TOKEN=${channels.slack.botToken ?? ''}`);
    lines.push(`SLACK_SIGNING_SECRET=${channels.slack.signingSecret ?? ''}`);
    if (channels.slack.appToken) lines.push(`SLACK_APP_TOKEN=${channels.slack.appToken}`);
  }

  lines.push('');
  writeFileSync(path, lines.join('\n'), { mode: 0o600 });
  return path;
}

/**
 * Resolve effective channel routing: for each platform, return the target
 * agent slug. Falls back to 'hermes' when no explicit routing is configured.
 */
function buildChannelRouting(secrets: EveSecrets): Record<string, string> {
  const platforms = ['telegram', 'discord', 'whatsapp', 'signal', 'matrix', 'slack'] as const;
  const result: Record<string, string> = {};
  for (const p of platforms) {
    result[p] = secrets.channelRouting?.[p] ?? 'hermes';
  }
  return result;
}

// ---------------------------------------------------------------------------
// Hermes config + Synap memory plugin generation
// ---------------------------------------------------------------------------

const HERMES_CONFIG_YAML = (
  model: string,
  baseUrl: string,
  apiKey: string,
  apiServerKey: string,
) => `# Hermes config — managed by Eve (eve install / eve ai apply)
# Editing this file directly is fine; Eve will overwrite the managed sections on the next apply.

memory:
  # Synap memory provider: 100% of memory syncs go to the Data Pod.
  # The synap plugin lives at $HERMES_HOME/plugins/memory/synap/
  provider: synap

model:
  name: ${model}
  base_url: ${baseUrl}
  api_key: ${apiKey}

# OpenAI-compat API gateway — OpenWebUI, LobeChat, LibreChat connect here.
# Port 8642 is exposed by docker-compose; clients reach it at hermes.<your-domain>
# or directly at http://eve-builder-hermes:8642 from within eve-network.
api_server:
  enabled: true
  port: 8642
  key: ${apiServerKey}
  host: 0.0.0.0

# MCP server — exposes Hermes tools to Claude Code, Cursor, and any MCP client.
# Connect at http://localhost:9120 (host) or http://eve-builder-hermes:9120 (docker network).
mcp:
  server:
    enabled: true
    port: 9120
    host: 0.0.0.0

# Hermes dashboard — admin UI
dashboard:
  port: 9119

# Skills — Synap Hub Protocol reference docs (mounted from ~/.eve/skills)
skills:
  dir: /opt/data/skills
`;

/**
 * Writes `~/.eve/hermes/config.yaml` — Hermes picks this up at startup
 * (via HERMES_HOME=/opt/data → /opt/data/config.yaml inside container,
 * which maps to ~/.eve/hermes/config.yaml on the host).
 *
 * Sets `memory.provider: synap` so every conversation turn is forwarded
 * to the Synap Data Pod via the plugin. Model block points Hermes at
 * Synap IS as the OpenAI-compat backend (same hub used by all components).
 */
export async function writeHermesConfigYaml(cwd: string = process.cwd()): Promise<string> {
  const secrets = await readEveSecrets(cwd);
  const synapUrl = resolveSynapUrl(secrets);
  const synapApiKey = await readAgentKeyOrLegacy('hermes', cwd);

  // Resolve model — honour per-service override in secrets.ai.serviceModels.
  // Default to synap/balanced (tier alias → IS routes to best available model).
  const serviceModels = secrets?.ai?.serviceModels ?? {};
  const model = serviceModels['hermes'] ?? 'synap/balanced';
  const baseUrl = synapUrl ? `${synapUrl.replace(/\/$/, '')}/v1` : 'http://eve-brain-synap:4000/v1';

  // Reuse the stable API server key (same one written to hermes.env).
  const apiServerKey = secrets?.builder?.hermes?.apiServerKey ?? '';

  const hermesDir = join(homedir(), '.eve', 'hermes');
  mkdirSync(hermesDir, { recursive: true });
  const configPath = join(hermesDir, 'config.yaml');
  writeFileSync(configPath, HERMES_CONFIG_YAML(model, baseUrl, synapApiKey, apiServerKey), { mode: 0o600 });
  return configPath;
}

// ---------------------------------------------------------------------------
// Synap memory provider plugin (Python)
// ---------------------------------------------------------------------------

const SYNAP_PLUGIN_YAML = `name: synap
version: 1.0.0
description: Synap Data Pod memory provider — routes all Hermes memory operations to the Synap Hub Protocol
hooks:
  - sync_turn
  - on_session_end
  - on_memory_write
  - prefetch
`;

const SYNAP_PROVIDER_PY = `"""
Synap Data Pod — Hermes MemoryProvider plugin.

Generated by Eve (eve install / eve ai apply). Do not edit manually;
re-run the install flow to regenerate.

This plugin receives 100% of Hermes memory syncs and forwards them to
the Synap Data Pod via Hub Protocol. Hermes enforces a single-provider
constraint so every conversation turn, session summary, and memory write
lands in Synap — no local SQLite divergence.

Env vars read at runtime (injected by Eve into hermes.env):
  SYNAP_API_KEY   — Hub Protocol bearer token (hermes agent identity)
  HUB_BASE_URL    — e.g. https://pod.example.com/api/hub
"""
import os
import json
import urllib.request
import urllib.parse
import urllib.error
from typing import Any


def _hub_url(path: str) -> str:
    base = os.environ.get("HUB_BASE_URL", "").rstrip("/")
    return f"{base}{path}"


def _headers() -> dict[str, str]:
    return {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {os.environ.get('SYNAP_API_KEY', '')}",
    }


def _post(path: str, payload: dict) -> dict | None:
    try:
        data = json.dumps(payload).encode()
        req = urllib.request.Request(_hub_url(path), data=data, headers=_headers(), method="POST")
        with urllib.request.urlopen(req, timeout=10) as resp:
            return json.loads(resp.read())
    except (urllib.error.URLError, Exception):
        return None


def _get(path: str) -> dict | None:
    try:
        req = urllib.request.Request(_hub_url(path), headers=_headers(), method="GET")
        with urllib.request.urlopen(req, timeout=10) as resp:
            return json.loads(resp.read())
    except (urllib.error.URLError, Exception):
        return None


class SynapMemoryProvider:
    """Synap Data Pod — Hermes MemoryProvider contract."""

    def __init__(self):
        self._session_id: str | None = None

    def is_available(self) -> bool:
        return bool(os.environ.get("SYNAP_API_KEY")) and bool(os.environ.get("HUB_BASE_URL"))

    def initialize(self, session_id: str, **kwargs) -> None:
        self._session_id = session_id

    def prefetch(self, query: str) -> list[dict]:
        """Return relevant memories from Synap for the given query.

        Uses GET /memory?query=X — full-text search backed by knowledge_facts.
        userId is resolved from the Bearer token (SYNAP_API_KEY = hermes agent).
        """
        if not query:
            return []
        try:
            encoded_query = urllib.parse.quote(query)
            encoded_session = urllib.parse.quote(self._session_id or "")
            url = _hub_url(f"/memory?query={encoded_query}&limit=10&sessionId={encoded_session}")
            req = urllib.request.Request(url, headers=_headers(), method="GET")
            with urllib.request.urlopen(req, timeout=10) as resp:
                items = json.loads(resp.read())
                if isinstance(items, list):
                    return items
        except Exception:
            pass
        return []

    def sync_turn(self, user: str, assistant: str) -> None:
        """Persist a conversation turn as two memory facts."""
        session_tag = f"[session:{self._session_id}]" if self._session_id else ""
        if user:
            _post("/memory", {"fact": f"{session_tag}[user] {user}"})
        if assistant:
            _post("/memory", {"fact": f"{session_tag}[assistant] {assistant}"})

    def on_session_end(self, messages: list[dict]) -> None:
        """Summarise the session as a single memory fact."""
        if not messages:
            return
        parts = []
        for m in messages[-20:]:  # cap at last 20 to avoid huge facts
            role = m.get("role", "?")
            content = str(m.get("content", ""))[:300]
            parts.append(f"{role}: {content}")
        summary = " | ".join(parts)
        session_tag = f"[session:{self._session_id}] " if self._session_id else ""
        _post("/memory", {"fact": f"{session_tag}[summary] {summary}", "confidence": 0.9})

    def on_memory_write(self, action: str, target: str, content: str) -> None:
        """Intercept explicit remember/update commands — store as facts."""
        if action in ("remember", "add", "update", "replace"):
            _post("/memory", {"fact": content, "confidence": 1.0})

    def get_tool_schemas(self) -> list[dict]:
        return []

    def handle_tool_call(self, name: str, args: dict) -> Any:
        return None


def register(ctx):
    ctx.register_memory_provider(SynapMemoryProvider())
`;

/**
 * Generates the Synap memory provider plugin into `~/.eve/hermes/plugins/memory/synap/`:
 *   - plugin.yaml  — Hermes plugin manifest
 *   - __init__.py  — MemoryProvider implementation (pure stdlib, no deps)
 *
 * The plugin dir is volume-mounted into the Hermes container at
 * $HERMES_HOME/plugins/memory/synap/ so the official image picks it up
 * without any custom Dockerfile.
 */
export function generateSynapPlugin(): { pluginDir: string } {
  const pluginDir = join(homedir(), '.eve', 'hermes', 'plugins', 'memory', 'synap');
  mkdirSync(pluginDir, { recursive: true });
  writeFileSync(join(pluginDir, 'plugin.yaml'), SYNAP_PLUGIN_YAML, 'utf-8');
  writeFileSync(join(pluginDir, '__init__.py'), SYNAP_PROVIDER_PY, 'utf-8');
  return { pluginDir };
}
