import { randomBytes } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { EveSecrets } from './secrets-contract.js';
import { readEveSecrets, writeEveSecrets } from './secrets-contract.js';

export interface OpenwebuiBootstrapResult {
  secrets: EveSecrets;
  generated: {
    adminEmail: boolean;
    adminPassword: boolean;
    adminName: boolean;
  };
}

export interface WriteOpenwebuiEnvOptions {
  synapApiKey: string;
  synapIsUrl: string;
  webuiUrl: string;
  webuiName?: string;
  adminEmail: string;
  adminPassword: string;
  adminName: string;
}

export interface WriteOpenwebuiEnvResult {
  envPath: string;
  secretKeyGenerated: boolean;
}

const DEFAULT_ADMIN_EMAIL = 'admin@eve.local';
const DEFAULT_ADMIN_NAME = 'Eve Admin';

function generatePassword(): string {
  return randomBytes(32).toString('base64url');
}

function parseEnv(content: string): Map<string, string> {
  const values = new Map<string, string>();
  for (const rawLine of content.split('\n')) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#') || !line.includes('=')) continue;
    const eq = line.indexOf('=');
    values.set(line.slice(0, eq), line.slice(eq + 1));
  }
  return values;
}

/**
 * Ensure OpenWebUI can complete first admin bootstrap without a human signup.
 *
 * The values are generated once and then reused so OpenWebUI can be recreated
 * idempotently without credential drift.
 */
export async function ensureOpenWebuiBootstrapSecrets(
  cwd: string = process.cwd(),
): Promise<OpenwebuiBootstrapResult> {
  const current = await readEveSecrets(cwd);
  const existing = current?.builder?.openwebui;
  const adminEmail = existing?.adminEmail?.trim() || DEFAULT_ADMIN_EMAIL;
  const adminPassword = existing?.adminPassword?.trim() || generatePassword();
  const adminName = existing?.adminName?.trim() || DEFAULT_ADMIN_NAME;

  const needsWrite =
    adminEmail !== existing?.adminEmail ||
    adminPassword !== existing?.adminPassword ||
    adminName !== existing?.adminName;

  const generated = {
    adminEmail: !existing?.adminEmail,
    adminPassword: !existing?.adminPassword,
    adminName: !existing?.adminName,
  };

  if (!needsWrite && current) {
    return { secrets: current, generated };
  }

  const next = await writeEveSecrets({
    builder: {
      ...(current?.builder ?? {}),
      openwebui: {
        ...(existing ?? {}),
        adminEmail,
        adminPassword,
        adminName,
      },
    },
  }, cwd);
  return { secrets: next, generated };
}

/**
 * Write the OpenWebUI env file for first boot and container env injection.
 *
 * Existing unknown keys are preserved. Eve-owned keys are rewritten from the
 * centralized secrets/config each time install/update/apply runs.
 */
export function writeOpenwebuiEnv(
  deployDir: string,
  options: WriteOpenwebuiEnvOptions,
): WriteOpenwebuiEnvResult {
  mkdirSync(deployDir, { recursive: true });
  const envPath = join(deployDir, '.env');
  const existing = existsSync(envPath) ? parseEnv(readFileSync(envPath, 'utf-8')) : new Map<string, string>();
  const secretKeyGenerated = !existing.get('WEBUI_SECRET_KEY')?.trim();

  const managed: Record<string, string> = {
    WEBUI_NAME: options.webuiName ?? 'Eve',
    WEBUI_URL: options.webuiUrl,
    SYNAP_API_KEY: options.synapApiKey,
    SYNAP_IS_URL: options.synapIsUrl,
    OLLAMA_BASE_URL: 'http://eve-brain-ollama:11434',
    ENABLE_SIGNUP: 'true',
    DEFAULT_USER_ROLE: 'pending',
    ENABLE_PERSISTENT_CONFIG: 'true',
    WEBUI_ADMIN_EMAIL: options.adminEmail,
    WEBUI_ADMIN_PASSWORD: options.adminPassword,
    WEBUI_ADMIN_NAME: options.adminName,
    WEBUI_SECRET_KEY: existing.get('WEBUI_SECRET_KEY')?.trim() || randomBytes(32).toString('hex'),
  };

  const unknown: string[] = [];
  for (const [key, value] of existing.entries()) {
    if (!(key in managed)) unknown.push(`${key}=${value}`);
  }

  const lines = [
    '# Open WebUI — generated by @eve/lifecycle',
    '# Eve rewrites managed keys on install/update. Custom keys are preserved.',
    '',
    '# Eve-managed headless bootstrap',
    ...Object.entries(managed).map(([key, value]) => `${key}=${value}`),
    ...(unknown.length ? ['', '# Preserved custom values', ...unknown] : []),
  ];

  writeFileSync(envPath, lines.join('\n') + '\n', { mode: 0o600 });
  return { envPath, secretKeyGenerated };
}
