/**
 * Eve-managed `docker-compose.override.yml` for the Synap pod.
 *
 * # Why this file exists
 *
 * The synap-backend container deliberately exposes its API only on the
 * Docker bridge network — no host port mapping, traffic flows through
 * Traefik to the public domain. That's correct for production: the host
 * doesn't need 4000 open, the firewall is simpler, only Traefik ever
 * sees external requests.
 *
 * But the on-host Eve CLI ALSO needs to talk to that API (auth provision,
 * doctor probes, lifecycle hooks, builder workspace seeding). Going
 * through the public domain to reach a service running 50ms away on the
 * same box is brittle: it fails when DNS isn't configured yet, when the
 * cert isn't minted yet, when split-DNS is in play, when the firewall
 * blocks loopback-to-public. We chased two days of phantom 404s through
 * exactly this path before realising the transport itself was wrong.
 *
 * The fix is the standard pattern every comparable system uses (Vault,
 * Consul, Caddy admin, K8s apiserver): bind the admin/API port on the
 * host's loopback interface so anyone WITH host access can reach it
 * directly, but no external client can. Compose makes this trivial:
 * `127.0.0.1:4000:4000` — the `127.0.0.1:` prefix is the magic, it
 * binds ONLY to loopback, not to all interfaces. The host firewall, the
 * docker bridge, the public network are all unaffected.
 *
 * We can't (won't) edit synap-backend's `docker-compose.yml` directly —
 * that file is regenerated by the synap install path and is owned by the
 * synap repo. Instead we use Compose's official extension hook,
 * `docker-compose.override.yml`, which is auto-merged on every
 * `docker compose` invocation in the same directory.
 *
 * # Idempotency + safety
 *
 * Two failure modes worth handling:
 *
 *   1. **The user has their own override.** If the file exists without
 *      our marker, we leave it alone and log a warning. They likely have
 *      a reason for it; clobbering would be hostile. The CLI falls back
 *      to the public URL, exactly as before.
 *
 *   2. **An older Eve install left a stale override.** The marker
 *      detection means we only refresh files we know we wrote. The
 *      check is a literal substring match for a long magic string —
 *      cheap and impossible to accidentally collide with.
 *
 * The function is idempotent: writing the same content twice produces
 * the same bytes on disk, and Compose's file-watch + container-recreate
 * is a no-op when content is unchanged.
 *
 * # Port choice
 *
 * `4000` — same port the backend listens on inside the container. Eve's
 * bundled `secrets.json.example` and most existing installs already
 * store `apiUrl: "http://127.0.0.1:4000"`, so binding the same port on
 * host loopback means the URL the user already has is the URL that
 * works. No new port to remember, no migration needed.
 *
 * On a production pod host nothing else competes for :4000 — the
 * synap-app dev server only collides on developer laptops, where Eve
 * isn't installed anyway.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { SYNAP_HOST_LOOPBACK_PORT } from "./components.js";

/**
 * Magic marker in the generated override file. We grep for this to
 * decide "is this file ours, can we refresh it?" — long enough that an
 * accidental match in a hand-written override would be deeply unlikely.
 */
const OVERRIDE_MARKER = "eve-managed:synap-loopback-override:v1";

const OVERRIDE_CONTENT = `# Eve-managed docker-compose override — DO NOT edit by hand.
#
# Marker: ${OVERRIDE_MARKER}
#
# Adds a loopback-only host port mapping so the on-host Eve CLI can
# reach the synap-backend HTTP API directly via 127.0.0.1:${SYNAP_HOST_LOOPBACK_PORT}, bypassing
# Traefik (faster, works before the public cert/DNS are healthy, and
# fails over to the public URL automatically when this isn't reachable).
#
# 127.0.0.1: prefix is the safety: binds ONLY to host loopback. External
# network, docker bridge, and the host firewall see nothing — anyone WITH
# host access (already root-equivalent for /opt/synap-backend) can reach
# port ${SYNAP_HOST_LOOPBACK_PORT} on localhost; nobody else can.
#
# This file is regenerated by 'eve setup synap' and 'eve update synap'.
# To opt out: delete the marker line above and Eve will leave the file
# alone (the CLI silently falls back to the public URL).
#
# See: synap-team-docs/content/team/devops/eve-cli-transports.mdx

services:
  backend:
    ports:
      - "127.0.0.1:${SYNAP_HOST_LOOPBACK_PORT}:4000"
`;

export interface EnsureOverrideResult {
  path: string;
  /** "wrote" = created or refreshed by us; "kept" = user-owned, untouched. */
  outcome: "wrote" | "kept";
  /** Reason "kept" was returned, for logging. Undefined when we wrote. */
  reason?: string;
}

/**
 * Idempotently write `${deployDir}/docker-compose.override.yml` so the
 * synap-backend container exposes a loopback-only host port.
 *
 * - File missing → write our content.
 * - File present, our marker found → refresh content (idempotent).
 * - File present, no marker → leave alone, return reason for caller logging.
 *
 * Caller is responsible for triggering `docker compose up -d backend`
 * after this function changes anything; on update flows that's already
 * happening as the next step, so there's no need to special-case it.
 */
export function ensureSynapLoopbackOverride(deployDir: string): EnsureOverrideResult {
  const path = join(deployDir, "docker-compose.override.yml");

  if (!existsSync(path)) {
    writeFileSync(path, OVERRIDE_CONTENT, "utf-8");
    return { path, outcome: "wrote" };
  }

  let existing = "";
  try {
    existing = readFileSync(path, "utf-8");
  } catch {
    // Unreadable — treat as user-owned. Don't try to fix permissions.
    return { path, outcome: "kept", reason: "could not read existing override file" };
  }

  if (existing.includes(OVERRIDE_MARKER)) {
    if (existing === OVERRIDE_CONTENT) {
      return { path, outcome: "wrote" };
    }
    writeFileSync(path, OVERRIDE_CONTENT, "utf-8");
    return { path, outcome: "wrote" };
  }

  return {
    path,
    outcome: "kept",
    reason:
      "user-owned docker-compose.override.yml present (no Eve marker) — " +
      `loopback port ${SYNAP_HOST_LOOPBACK_PORT} not added; CLI will use public URL`,
  };
}
