import { spawn } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { readEveSecrets, writeBuilderProjectEnv, ensureEveSkillsLayout, defaultSkillsDir } from '@eve/dna';

export class OpenCodeService {
  private isInstalled = false;
  private projectPath: string | null = null;

  async install(): Promise<void> {
    console.log('Installing OpenCode...');
    const check = spawn('sh', ['-c', 'which opencode'], { stdio: ['pipe', 'pipe', 'ignore'] });
    await new Promise<void>((resolve, reject) => {
      check.on('close', (code) => {
        if (code === 0) {
          console.log('OpenCode already installed');
          resolve();
        } else {
          // Install OpenCode CLI
          console.log('Installing OpenCode CLI...');
          const npm = spawn('sh', ['-c', 'npm install -g @opencode/cli'], {
            stdio: 'inherit',
          });
          npm.on('close', (code) => {
            if (code && code !== 0) reject(new Error(`npm install failed with code ${code}`));
            else resolve();
          });
          npm.on('error', reject);
        }
      });
      check.on('error', reject);
    });
    this.isInstalled = true;
    console.log('OpenCode installed successfully');
  }

  async initProject(name: string, template?: string): Promise<void> {
    if (!this.isInstalled) {
      await this.install();
    }

    console.log(`Initializing OpenCode project: ${name}`);

    const secrets = await readEveSecrets(process.cwd());
    const workspaceRoot = secrets?.builder?.workspaceDir ?? join(homedir(), '.eve', 'workspace');
    mkdirSync(workspaceRoot, { recursive: true });
    const projectDir = join(workspaceRoot, name);
    if (!existsSync(projectDir)) {
      mkdirSync(projectDir, { recursive: true });
    }
    this.projectPath = projectDir;

    // Create OpenCode config
    const config = {
      name,
      template: template || 'default',
      version: '0.1.0',
      createdAt: new Date().toISOString(),
      features: ['docs', 'website', 'blog'],
    };

    writeFileSync(
      join(projectDir, 'opencode.config.json'),
      JSON.stringify(config, null, 2)
    );

    // Create basic structure
    const dirs = ['src', 'docs', 'public', 'templates'];
    for (const dir of dirs) {
      mkdirSync(join(projectDir, dir), { recursive: true });
    }

    // Create entry point
    writeFileSync(
      join(projectDir, 'src', 'index.md'),
      `# ${name}\n\nGenerated by OpenCode via eve Builder\n`
    );

    const skillsDir = secrets?.builder?.skillsDir ?? defaultSkillsDir();
    ensureEveSkillsLayout(skillsDir);
    await writeBuilderProjectEnv(projectDir, process.cwd());

    console.log(`Project initialized at: ${projectDir}`);
  }

  async generate(): Promise<void> {
    if (!this.projectPath) {
      throw new Error('No project initialized. Call initProject first.');
    }

    console.log('Generating content with OpenCode...');

    return new Promise<void>((resolve, reject) => {
      const cmd = `opencode generate`;
      const proc = spawn('sh', ['-c', cmd], {
        cwd: this.projectPath ?? undefined,
        stdio: ['inherit', 'inherit', 'inherit'],
      });

      proc.on('close', (code: number | null) => {
        if (code === 0) {
          console.log('Content generated successfully');
          resolve();
        } else {
          const err = new Error(`Generation exited with code ${code ?? 1}`);
          console.error(err);
          reject(err);
        }
      });

      proc.on('error', reject);
    });
  }

  async build(): Promise<void> {
    if (!this.projectPath) {
      throw new Error('No project initialized. Call initProject first.');
    }

    console.log('Building OpenCode project...');

    return new Promise<void>((resolve, reject) => {
      const cmd = `opencode build`;
      const proc = spawn('sh', ['-c', cmd], {
        cwd: this.projectPath ?? undefined,
        stdio: ['inherit', 'inherit', 'inherit'],
      });

      proc.on('close', (code: number | null) => {
        if (code === 0) {
          console.log('Build completed successfully');
          resolve();
        } else {
          const err = new Error(`Build exited with code ${code ?? 1}`);
          console.error(err);
          reject(err);
        }
      });

      proc.on('error', reject);
    });
  }

  getProjectPath(): string | null {
    return this.projectPath;
  }
}
