import { execSync } from 'child_process';
import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { homedir } from 'os';
import { join } from 'path';
import { readEveSecrets, writeBuilderProjectEnv, ensureEveSkillsLayout, defaultSkillsDir } from '@eve/dna';

export class OpenCodeService {
  private isInstalled = false;
  private projectPath: string | null = null;

  async install(): Promise<void> {
    console.log('Installing OpenCode...');
    try {
      // Check if OpenCode is already available
      execSync('which opencode', { stdio: 'ignore' });
      console.log('OpenCode already installed');
    } catch {
      // Install OpenCode CLI
      console.log('Installing OpenCode CLI...');
      execSync('npm install -g @opencode/cli', { stdio: 'inherit' });
    }
    this.isInstalled = true;
    console.log('OpenCode installed successfully');
  }

  async initProject(name: string, template?: string): Promise<void> {
    if (!this.isInstalled) {
      await this.install();
    }

    console.log(`Initializing OpenCode project: ${name}`);
    
    const secrets = await readEveSecrets(process.cwd());
    const workspaceRoot = secrets?.builder?.workspaceDir ?? join(homedir(), '.eve', 'workspace');
    mkdirSync(workspaceRoot, { recursive: true });
    const projectDir = join(workspaceRoot, name);
    if (!existsSync(projectDir)) {
      mkdirSync(projectDir, { recursive: true });
    }
    this.projectPath = projectDir;

    // Create OpenCode config
    const config = {
      name,
      template: template || 'default',
      version: '0.1.0',
      createdAt: new Date().toISOString(),
      features: ['docs', 'website', 'blog'],
    };

    writeFileSync(
      join(projectDir, 'opencode.config.json'),
      JSON.stringify(config, null, 2)
    );

    // Create basic structure
    const dirs = ['src', 'docs', 'public', 'templates'];
    for (const dir of dirs) {
      mkdirSync(join(projectDir, dir), { recursive: true });
    }

    // Create entry point
    writeFileSync(
      join(projectDir, 'src', 'index.md'),
      `# ${name}\n\nGenerated by OpenCode via eve Builder\n`
    );

    const skillsDir = secrets?.builder?.skillsDir ?? defaultSkillsDir();
    ensureEveSkillsLayout(skillsDir);
    await writeBuilderProjectEnv(projectDir, process.cwd());

    console.log(`Project initialized at: ${projectDir}`);
  }

  async generate(): Promise<void> {
    if (!this.projectPath) {
      throw new Error('No project initialized. Call initProject first.');
    }

    console.log('Generating content with OpenCode...');
    
    // Run OpenCode generation
    try {
      execSync('opencode generate', { 
        cwd: this.projectPath,
        stdio: 'inherit' 
      });
      console.log('Content generated successfully');
    } catch (error) {
      console.error('Generation failed:', error);
      throw error;
    }
  }

  async build(): Promise<void> {
    if (!this.projectPath) {
      throw new Error('No project initialized. Call initProject first.');
    }

    console.log('Building OpenCode project...');
    
    try {
      execSync('opencode build', { 
        cwd: this.projectPath,
        stdio: 'inherit' 
      });
      console.log('Build completed successfully');
    } catch (error) {
      console.error('Build failed:', error);
      throw error;
    }
  }

  getProjectPath(): string | null {
    return this.projectPath;
  }
}
